/*
 * amp.h -- Asymmetric multiprocessing helpers for Zynq-7000 dual-A9.
 *
 * Core 0 copies the embedded core-1 image into DDR and wakes CPU1.
 */

#ifndef AMP_H
#define AMP_H

#include <stdint.h>

/* Default core-1 entry address, matched against the core-1 firmware's
 * linker script (vitis_workspace/frontend_core1/src/lscript.ld which
 * is patched to ORIGIN=0x20000000 by create_vitis_workspace.py). */
#define AMP_CORE1_ENTRY_DEFAULT  0x20000000U

/* Copy core 1's binary image into DDR at AMP_CORE1_ENTRY_DEFAULT,
 * dcache-flush the destination, publish the CPU1 boot vector, and wake CPU1.
 * Returns the size copied (in bytes). The blob is embedded into core 0's image
 * by lib/core1_blob.S (generated by create_vitis_workspace.py from the
 * frontend_core1.elf). */
uint32_t amp_release_core1(void);

#endif /* AMP_H */
