/* Generated by scripts/gen_applicard_rom_c.py -- do not edit.
 *
 * PCPI Appli-Card Z80 boot ROM (applicard-v9.bin), 2 KB,
 * CRC32 1d461000. Source dump: Apple II Documentation Project /
 * MAME romset a2applicard.
 */

#ifndef APPLICARD_ROM_H
#define APPLICARD_ROM_H

#include <stdint.h>

#define APPLICARD_ROM_BYTES 2048U

extern const uint8_t applicard_rom[APPLICARD_ROM_BYTES];

#endif /* APPLICARD_ROM_H */
