#ifndef BOOT_MENU_ROM_PATCH_H
#define BOOT_MENU_ROM_PATCH_H

#include <stdint.h>

/* Generated by scripts/build_boot_menu_rom.py from software/boot_menu_slot7.a65. */
#define BOOT_MENU_C8_PATCH_DELAY_X_OFFSET       0xD4U
#define BOOT_MENU_C8_PATCH_DELAY_Y_OFFSET       0xD6U
#define BOOT_MENU_C8_PATCH_IIPLUS_VAPOR_X_OFFSET 0x59U
#define BOOT_MENU_C8_PATCH_IIPLUS_VAPOR_Y_OFFSET 0x5BU

#define BOOT_MENU_C8_DELAY_NTSC_X               0x1DU
#define BOOT_MENU_C8_DELAY_NTSC_Y               0x74U
#define BOOT_MENU_C8_DELAY_PAL_X                0x54U
#define BOOT_MENU_C8_DELAY_PAL_Y                0x2FU
#define BOOT_MENU_C8_IIPLUS_VAPOR_X             0x02U
#define BOOT_MENU_C8_IIPLUS_VAPOR_Y             0x04U

#define BOOT_MENU_C8_DELAY_NTSC_BODY_CYCLES     17014U
#define BOOT_MENU_C8_DELAY_PAL_BODY_CYCLES      20264U

#endif /* BOOT_MENU_ROM_PATCH_H */
