/* SPDX-License-Identifier: GPL-3.0-only */
/* USB3300 host policy from hasseily/multitini-one, commit c2b87fa. */
#ifndef APPLETINI_CHERRYUSB_ULPI_H
#define APPLETINI_CHERRYUSB_ULPI_H

#include <stdint.h>

/* Zynq-7000 ULPI viewport commands. RW=1 is a PHY-register write. */
#define CHERRYUSB_ULPI_VIEW_DATWR_MASK UINT32_C(0x000000FF)
#define CHERRYUSB_ULPI_VIEW_DATRD_MASK UINT32_C(0x0000FF00)
#define CHERRYUSB_ULPI_VIEW_ADDR_MASK  UINT32_C(0x00FF0000)
#define CHERRYUSB_ULPI_VIEW_WRITE      UINT32_C(0x20000000)
#define CHERRYUSB_ULPI_VIEW_RUN        UINT32_C(0x40000000)
#define CHERRYUSB_ULPI_VIEW_WAKEUP     UINT32_C(0x80000000)

/* USB3300 immediate register set. */
#define CHERRYUSB_ULPI_REG_VENDOR_LOW       UINT8_C(0x00)
#define CHERRYUSB_ULPI_REG_VENDOR_HIGH      UINT8_C(0x01)
#define CHERRYUSB_ULPI_REG_PRODUCT_LOW      UINT8_C(0x02)
#define CHERRYUSB_ULPI_REG_PRODUCT_HIGH     UINT8_C(0x03)
#define CHERRYUSB_ULPI_REG_FUNCTION_CONTROL UINT8_C(0x04)
#define CHERRYUSB_ULPI_REG_FUNCTION_SET     UINT8_C(0x05)
#define CHERRYUSB_ULPI_REG_INTERFACE_CONTROL UINT8_C(0x07)
#define CHERRYUSB_ULPI_REG_INTERFACE_SET    UINT8_C(0x08)
#define CHERRYUSB_ULPI_REG_INTERFACE_CLEAR  UINT8_C(0x09)
#define CHERRYUSB_ULPI_REG_OTG_CONTROL      UINT8_C(0x0A)
#define CHERRYUSB_ULPI_REG_OTG_SET          UINT8_C(0x0B)
#define CHERRYUSB_ULPI_REG_OTG_CLEAR        UINT8_C(0x0C)
#define CHERRYUSB_ULPI_REG_INTERRUPT_RISING_SET UINT8_C(0x0E)
#define CHERRYUSB_ULPI_REG_INTERRUPT_FALLING_SET UINT8_C(0x11)
#define CHERRYUSB_ULPI_REG_INTERRUPT_STATUS UINT8_C(0x13)
#define CHERRYUSB_ULPI_REG_DEBUG            UINT8_C(0x15)

#define CHERRYUSB_ULPI_FUNCTION_HOST UINT8_C(0x41)
#define CHERRYUSB_ULPI_FUNCTION_SUSPENDM UINT8_C(0x40)

#define CHERRYUSB_ULPI_INTERFACE_AUTORESUME           UINT8_C(0x10)
#define CHERRYUSB_ULPI_INTERFACE_INDICATOR_COMPLEMENT UINT8_C(0x20)
#define CHERRYUSB_ULPI_INTERFACE_INDICATOR_PASSTHRU   UINT8_C(0x40)
#define CHERRYUSB_ULPI_INTERFACE_HOST_SET \
    CHERRYUSB_ULPI_INTERFACE_AUTORESUME
#define CHERRYUSB_ULPI_INTERFACE_HOST_CLEAR \
    (CHERRYUSB_ULPI_INTERFACE_INDICATOR_COMPLEMENT | \
     CHERRYUSB_ULPI_INTERFACE_INDICATOR_PASSTHRU)

#define CHERRYUSB_ULPI_OTG_ID_PULLUP       UINT8_C(0x01)
#define CHERRYUSB_ULPI_OTG_DP_PULLDOWN     UINT8_C(0x02)
#define CHERRYUSB_ULPI_OTG_DM_PULLDOWN     UINT8_C(0x04)
#define CHERRYUSB_ULPI_OTG_DISCHRGVBUS     UINT8_C(0x08)
#define CHERRYUSB_ULPI_OTG_CHRGVBUS        UINT8_C(0x10)
#define CHERRYUSB_ULPI_OTG_DRVVBUS         UINT8_C(0x20)
#define CHERRYUSB_ULPI_OTG_DRVVBUS_EXT     UINT8_C(0x40)
#define CHERRYUSB_ULPI_OTG_EXTVBUSIND      UINT8_C(0x80)

#define CHERRYUSB_ULPI_OTG_HOST_SET \
    (CHERRYUSB_ULPI_OTG_DP_PULLDOWN | \
     CHERRYUSB_ULPI_OTG_DM_PULLDOWN | \
     CHERRYUSB_ULPI_OTG_DRVVBUS | \
     CHERRYUSB_ULPI_OTG_DRVVBUS_EXT)
#define CHERRYUSB_ULPI_OTG_HOST_CLEAR \
    (CHERRYUSB_ULPI_OTG_ID_PULLUP | \
     CHERRYUSB_ULPI_OTG_DISCHRGVBUS | \
     CHERRYUSB_ULPI_OTG_CHRGVBUS | \
     CHERRYUSB_ULPI_OTG_EXTVBUSIND)
#define CHERRYUSB_ULPI_OTG_HOST_BASE_SET \
    (CHERRYUSB_ULPI_OTG_DP_PULLDOWN | CHERRYUSB_ULPI_OTG_DM_PULLDOWN)
#define CHERRYUSB_ULPI_OTG_VBUS_DRIVE \
    (CHERRYUSB_ULPI_OTG_DRVVBUS | CHERRYUSB_ULPI_OTG_DRVVBUS_EXT)

#define CHERRYUSB_ULPI_INTERRUPT_VBUS_VALID UINT8_C(0x02)

static inline uint32_t cherryusb_ulpi_wakeup_command(void)
{
    return CHERRYUSB_ULPI_VIEW_WAKEUP | CHERRYUSB_ULPI_VIEW_WRITE;
}

static inline uint32_t cherryusb_ulpi_read_command(uint8_t address)
{
    return CHERRYUSB_ULPI_VIEW_RUN | ((uint32_t)address << 16);
}

static inline uint32_t cherryusb_ulpi_write_command(uint8_t address,
                                                     uint8_t value)
{
    return CHERRYUSB_ULPI_VIEW_RUN | CHERRYUSB_ULPI_VIEW_WRITE |
           ((uint32_t)address << 16) | (uint32_t)value;
}

static inline uint8_t cherryusb_usb3300_host_otg_control(uint8_t current)
{
    current &= (uint8_t)~CHERRYUSB_ULPI_OTG_HOST_CLEAR;
    current |= CHERRYUSB_ULPI_OTG_HOST_SET;
    return current;
}

static inline uint8_t cherryusb_usb3300_host_interface_control(
    uint8_t current)
{
    current &= (uint8_t)~CHERRYUSB_ULPI_INTERFACE_HOST_CLEAR;
    current |= CHERRYUSB_ULPI_INTERFACE_HOST_SET;
    return current;
}

static inline uint8_t cherryusb_usb3300_vbus_is_enabled(uint8_t otg_control)
{
    return ((otg_control & CHERRYUSB_ULPI_OTG_VBUS_DRIVE) != 0U) ?
        UINT8_C(1) : UINT8_C(0);
}

#endif /* APPLETINI_CHERRYUSB_ULPI_H */
