#ifndef DISK2_SOUND_SAMPLES_H
#define DISK2_SOUND_SAMPLES_H

#include <stdint.h>

#define DISK2_SOUND_SAMPLE_RATE_HZ 48000U
#define DISK2_SOUND_SAMPLE_COUNT 207484U
#define DISK2_SOUND_SAMPLE_BYTES (DISK2_SOUND_SAMPLE_COUNT * (uint32_t)sizeof(uint16_t))

#define DISK2_SOUND_ID_DOOR_OPEN 0U
#define DISK2_SOUND_ID_DOOR_CLOSE 1U
#define DISK2_SOUND_ID_TRACK0_RECAL 2U
#define DISK2_SOUND_ID_IDLE_SPIN 3U
#define DISK2_SOUND_ID_SEEK_34_0 4U
#define DISK2_SOUND_ID_SEEK_0_34 5U

extern const uint16_t disk2_sound_samples[DISK2_SOUND_SAMPLE_COUNT];

#endif
