#ifndef USB_CONFIG_H
#define USB_CONFIG_H

#include "cherryusb_platform.h"

#define CONFIG_USB_PRINTF(...) cherryusb_printf(__VA_ARGS__)
#define CONFIG_USB_DBG_LEVEL 2
#define CONFIG_USB_ASSERT_DISABLE

#define CONFIG_USB_ALIGN_SIZE 64
#define USB_MEM_ALIGNX __attribute__((aligned(CONFIG_USB_ALIGN_SIZE)))
#define USB_NOCACHE_RAM_SECTION

#define CONFIG_USBHOST_MAX_BUS 1
#define CONFIG_USBHOST_MAX_RHPORTS 1
#define CONFIG_USBHOST_MAX_EXTHUBS 4
#define CONFIG_USBHOST_MAX_EHPORTS 8
#define CONFIG_USBHOST_MAX_INTERFACES 8
#define CONFIG_USBHOST_MAX_INTF_ALTSETTINGS 2
#define CONFIG_USBHOST_MAX_ENDPOINTS 4
#define CONFIG_USBHOST_MAX_HID_CLASS 8
#define CONFIG_USB_HID_MAX_REPORT_ITEMS 48
#define CONFIG_USBHOST_DEV_NAMELEN 16
#define CONFIG_USBHOST_REQUEST_BUFFER_LEN 512
#define CONFIG_USBHOST_CONTROL_TRANSFER_TIMEOUT 1000
#define CONFIG_USBHOST_PSC_STACKSIZE 1024
#define CONFIG_USBHOST_PSC_PRIO 8

#define CONFIG_USB_EHCI_HCCR_OFFSET 0x100
#define CONFIG_USB_EHCI_FRAME_LIST_SIZE 1024
#define CONFIG_USB_EHCI_QH_NUM 16
#define CONFIG_USB_EHCI_QTD_NUM 64

#define CONFIG_USB_DCACHE_ENABLE
#define CONFIG_USB_EHCI_DESC_DCACHE_ENABLE

#endif /* USB_CONFIG_H */
