`timescale 1ns / 1ps

// Generated by scripts/build_disk2_sound_assets.py from Assets/Sounds/*.wav.
package disk2_sound_pkg;

    localparam int unsigned DISK2_SOUND_COUNT = 6;
    localparam int unsigned DISK2_SOUND_SAMPLE_COUNT = 207484;
    localparam int unsigned DISK2_SOUND_SAMPLE_RATE_HZ = 48000;

    localparam logic [2:0] DISK2_SOUND_DOOR_OPEN = 3'd0;
    localparam logic [2:0] DISK2_SOUND_DOOR_CLOSE = 3'd1;
    localparam logic [2:0] DISK2_SOUND_TRACK0_RECAL = 3'd2;
    localparam logic [2:0] DISK2_SOUND_IDLE_SPIN = 3'd3;
    localparam logic [2:0] DISK2_SOUND_SEEK_34_0 = 3'd4;
    localparam logic [2:0] DISK2_SOUND_SEEK_0_34 = 3'd5;

    function automatic logic [17:0] disk2_sound_offset(input logic [2:0] index);
        case (index)
            DISK2_SOUND_DOOR_OPEN: disk2_sound_offset = 18'd0;
            DISK2_SOUND_DOOR_CLOSE: disk2_sound_offset = 18'd21790;
            DISK2_SOUND_TRACK0_RECAL: disk2_sound_offset = 18'd41747;
            DISK2_SOUND_IDLE_SPIN: disk2_sound_offset = 18'd96937;
            DISK2_SOUND_SEEK_34_0: disk2_sound_offset = 18'd146780;
            DISK2_SOUND_SEEK_0_34: disk2_sound_offset = 18'd177132;
            default: disk2_sound_offset = 18'd0;
        endcase
    endfunction

    function automatic logic [17:0] disk2_sound_length(input logic [2:0] index);
        case (index)
            DISK2_SOUND_DOOR_OPEN: disk2_sound_length = 18'd21790;
            DISK2_SOUND_DOOR_CLOSE: disk2_sound_length = 18'd19957;
            DISK2_SOUND_TRACK0_RECAL: disk2_sound_length = 18'd55190;
            DISK2_SOUND_IDLE_SPIN: disk2_sound_length = 18'd49843;
            DISK2_SOUND_SEEK_34_0: disk2_sound_length = 18'd30352;
            DISK2_SOUND_SEEK_0_34: disk2_sound_length = 18'd30352;
            default: disk2_sound_length = 18'd0;
        endcase
    endfunction

    localparam logic [7:0] DISK2_SOUND_SEEK_FULL_QTRACK_DISTANCE = 8'd140;

    function automatic logic [17:0] disk2_sound_seek_position_offset(
        input logic [2:0] index,
        input logic [7:0] position
    );
        logic [7:0] capped_position;
        begin
            if (position > DISK2_SOUND_SEEK_FULL_QTRACK_DISTANCE)
                capped_position = DISK2_SOUND_SEEK_FULL_QTRACK_DISTANCE;
            else
                capped_position = position;

            unique case (index)
                DISK2_SOUND_SEEK_34_0: begin
                    unique case (capped_position)
                        8'd0: disk2_sound_seek_position_offset = 18'd0;
                        8'd1: disk2_sound_seek_position_offset = 18'd217;
                        8'd2: disk2_sound_seek_position_offset = 18'd434;
                        8'd3: disk2_sound_seek_position_offset = 18'd650;
                        8'd4: disk2_sound_seek_position_offset = 18'd867;
                        8'd5: disk2_sound_seek_position_offset = 18'd1084;
                        8'd6: disk2_sound_seek_position_offset = 18'd1301;
                        8'd7: disk2_sound_seek_position_offset = 18'd1518;
                        8'd8: disk2_sound_seek_position_offset = 18'd1734;
                        8'd9: disk2_sound_seek_position_offset = 18'd1951;
                        8'd10: disk2_sound_seek_position_offset = 18'd2168;
                        8'd11: disk2_sound_seek_position_offset = 18'd2385;
                        8'd12: disk2_sound_seek_position_offset = 18'd2602;
                        8'd13: disk2_sound_seek_position_offset = 18'd2818;
                        8'd14: disk2_sound_seek_position_offset = 18'd3035;
                        8'd15: disk2_sound_seek_position_offset = 18'd3252;
                        8'd16: disk2_sound_seek_position_offset = 18'd3469;
                        8'd17: disk2_sound_seek_position_offset = 18'd3686;
                        8'd18: disk2_sound_seek_position_offset = 18'd3902;
                        8'd19: disk2_sound_seek_position_offset = 18'd4119;
                        8'd20: disk2_sound_seek_position_offset = 18'd4336;
                        8'd21: disk2_sound_seek_position_offset = 18'd4553;
                        8'd22: disk2_sound_seek_position_offset = 18'd4770;
                        8'd23: disk2_sound_seek_position_offset = 18'd4986;
                        8'd24: disk2_sound_seek_position_offset = 18'd5203;
                        8'd25: disk2_sound_seek_position_offset = 18'd5420;
                        8'd26: disk2_sound_seek_position_offset = 18'd5637;
                        8'd27: disk2_sound_seek_position_offset = 18'd5854;
                        8'd28: disk2_sound_seek_position_offset = 18'd6070;
                        8'd29: disk2_sound_seek_position_offset = 18'd6287;
                        8'd30: disk2_sound_seek_position_offset = 18'd6504;
                        8'd31: disk2_sound_seek_position_offset = 18'd6721;
                        8'd32: disk2_sound_seek_position_offset = 18'd6938;
                        8'd33: disk2_sound_seek_position_offset = 18'd7154;
                        8'd34: disk2_sound_seek_position_offset = 18'd7371;
                        8'd35: disk2_sound_seek_position_offset = 18'd7588;
                        8'd36: disk2_sound_seek_position_offset = 18'd7805;
                        8'd37: disk2_sound_seek_position_offset = 18'd8022;
                        8'd38: disk2_sound_seek_position_offset = 18'd8238;
                        8'd39: disk2_sound_seek_position_offset = 18'd8455;
                        8'd40: disk2_sound_seek_position_offset = 18'd8672;
                        8'd41: disk2_sound_seek_position_offset = 18'd8889;
                        8'd42: disk2_sound_seek_position_offset = 18'd9106;
                        8'd43: disk2_sound_seek_position_offset = 18'd9322;
                        8'd44: disk2_sound_seek_position_offset = 18'd9539;
                        8'd45: disk2_sound_seek_position_offset = 18'd9756;
                        8'd46: disk2_sound_seek_position_offset = 18'd9973;
                        8'd47: disk2_sound_seek_position_offset = 18'd10190;
                        8'd48: disk2_sound_seek_position_offset = 18'd10406;
                        8'd49: disk2_sound_seek_position_offset = 18'd10623;
                        8'd50: disk2_sound_seek_position_offset = 18'd10840;
                        8'd51: disk2_sound_seek_position_offset = 18'd11057;
                        8'd52: disk2_sound_seek_position_offset = 18'd11274;
                        8'd53: disk2_sound_seek_position_offset = 18'd11490;
                        8'd54: disk2_sound_seek_position_offset = 18'd11707;
                        8'd55: disk2_sound_seek_position_offset = 18'd11924;
                        8'd56: disk2_sound_seek_position_offset = 18'd12141;
                        8'd57: disk2_sound_seek_position_offset = 18'd12358;
                        8'd58: disk2_sound_seek_position_offset = 18'd12574;
                        8'd59: disk2_sound_seek_position_offset = 18'd12791;
                        8'd60: disk2_sound_seek_position_offset = 18'd13008;
                        8'd61: disk2_sound_seek_position_offset = 18'd13225;
                        8'd62: disk2_sound_seek_position_offset = 18'd13442;
                        8'd63: disk2_sound_seek_position_offset = 18'd13658;
                        8'd64: disk2_sound_seek_position_offset = 18'd13875;
                        8'd65: disk2_sound_seek_position_offset = 18'd14092;
                        8'd66: disk2_sound_seek_position_offset = 18'd14309;
                        8'd67: disk2_sound_seek_position_offset = 18'd14526;
                        8'd68: disk2_sound_seek_position_offset = 18'd14742;
                        8'd69: disk2_sound_seek_position_offset = 18'd14959;
                        8'd70: disk2_sound_seek_position_offset = 18'd15176;
                        8'd71: disk2_sound_seek_position_offset = 18'd15393;
                        8'd72: disk2_sound_seek_position_offset = 18'd15610;
                        8'd73: disk2_sound_seek_position_offset = 18'd15826;
                        8'd74: disk2_sound_seek_position_offset = 18'd16043;
                        8'd75: disk2_sound_seek_position_offset = 18'd16260;
                        8'd76: disk2_sound_seek_position_offset = 18'd16477;
                        8'd77: disk2_sound_seek_position_offset = 18'd16694;
                        8'd78: disk2_sound_seek_position_offset = 18'd16910;
                        8'd79: disk2_sound_seek_position_offset = 18'd17127;
                        8'd80: disk2_sound_seek_position_offset = 18'd17344;
                        8'd81: disk2_sound_seek_position_offset = 18'd17561;
                        8'd82: disk2_sound_seek_position_offset = 18'd17778;
                        8'd83: disk2_sound_seek_position_offset = 18'd17994;
                        8'd84: disk2_sound_seek_position_offset = 18'd18211;
                        8'd85: disk2_sound_seek_position_offset = 18'd18428;
                        8'd86: disk2_sound_seek_position_offset = 18'd18645;
                        8'd87: disk2_sound_seek_position_offset = 18'd18862;
                        8'd88: disk2_sound_seek_position_offset = 18'd19078;
                        8'd89: disk2_sound_seek_position_offset = 18'd19295;
                        8'd90: disk2_sound_seek_position_offset = 18'd19512;
                        8'd91: disk2_sound_seek_position_offset = 18'd19729;
                        8'd92: disk2_sound_seek_position_offset = 18'd19946;
                        8'd93: disk2_sound_seek_position_offset = 18'd20162;
                        8'd94: disk2_sound_seek_position_offset = 18'd20379;
                        8'd95: disk2_sound_seek_position_offset = 18'd20596;
                        8'd96: disk2_sound_seek_position_offset = 18'd20813;
                        8'd97: disk2_sound_seek_position_offset = 18'd21030;
                        8'd98: disk2_sound_seek_position_offset = 18'd21246;
                        8'd99: disk2_sound_seek_position_offset = 18'd21463;
                        8'd100: disk2_sound_seek_position_offset = 18'd21680;
                        8'd101: disk2_sound_seek_position_offset = 18'd21897;
                        8'd102: disk2_sound_seek_position_offset = 18'd22114;
                        8'd103: disk2_sound_seek_position_offset = 18'd22330;
                        8'd104: disk2_sound_seek_position_offset = 18'd22547;
                        8'd105: disk2_sound_seek_position_offset = 18'd22764;
                        8'd106: disk2_sound_seek_position_offset = 18'd22981;
                        8'd107: disk2_sound_seek_position_offset = 18'd23198;
                        8'd108: disk2_sound_seek_position_offset = 18'd23414;
                        8'd109: disk2_sound_seek_position_offset = 18'd23631;
                        8'd110: disk2_sound_seek_position_offset = 18'd23848;
                        8'd111: disk2_sound_seek_position_offset = 18'd24065;
                        8'd112: disk2_sound_seek_position_offset = 18'd24282;
                        8'd113: disk2_sound_seek_position_offset = 18'd24498;
                        8'd114: disk2_sound_seek_position_offset = 18'd24715;
                        8'd115: disk2_sound_seek_position_offset = 18'd24932;
                        8'd116: disk2_sound_seek_position_offset = 18'd25149;
                        8'd117: disk2_sound_seek_position_offset = 18'd25366;
                        8'd118: disk2_sound_seek_position_offset = 18'd25582;
                        8'd119: disk2_sound_seek_position_offset = 18'd25799;
                        8'd120: disk2_sound_seek_position_offset = 18'd26016;
                        8'd121: disk2_sound_seek_position_offset = 18'd26233;
                        8'd122: disk2_sound_seek_position_offset = 18'd26450;
                        8'd123: disk2_sound_seek_position_offset = 18'd26666;
                        8'd124: disk2_sound_seek_position_offset = 18'd26883;
                        8'd125: disk2_sound_seek_position_offset = 18'd27100;
                        8'd126: disk2_sound_seek_position_offset = 18'd27317;
                        8'd127: disk2_sound_seek_position_offset = 18'd27534;
                        8'd128: disk2_sound_seek_position_offset = 18'd27750;
                        8'd129: disk2_sound_seek_position_offset = 18'd27967;
                        8'd130: disk2_sound_seek_position_offset = 18'd28184;
                        8'd131: disk2_sound_seek_position_offset = 18'd28401;
                        8'd132: disk2_sound_seek_position_offset = 18'd28618;
                        8'd133: disk2_sound_seek_position_offset = 18'd28834;
                        8'd134: disk2_sound_seek_position_offset = 18'd29051;
                        8'd135: disk2_sound_seek_position_offset = 18'd29268;
                        8'd136: disk2_sound_seek_position_offset = 18'd29485;
                        8'd137: disk2_sound_seek_position_offset = 18'd29702;
                        8'd138: disk2_sound_seek_position_offset = 18'd29918;
                        8'd139: disk2_sound_seek_position_offset = 18'd30135;
                        8'd140: disk2_sound_seek_position_offset = 18'd30352;
                        default: disk2_sound_seek_position_offset = 18'd30352;
                    endcase
                end
                DISK2_SOUND_SEEK_0_34: begin
                    unique case (capped_position)
                        8'd0: disk2_sound_seek_position_offset = 18'd0;
                        8'd1: disk2_sound_seek_position_offset = 18'd217;
                        8'd2: disk2_sound_seek_position_offset = 18'd434;
                        8'd3: disk2_sound_seek_position_offset = 18'd650;
                        8'd4: disk2_sound_seek_position_offset = 18'd867;
                        8'd5: disk2_sound_seek_position_offset = 18'd1084;
                        8'd6: disk2_sound_seek_position_offset = 18'd1301;
                        8'd7: disk2_sound_seek_position_offset = 18'd1518;
                        8'd8: disk2_sound_seek_position_offset = 18'd1734;
                        8'd9: disk2_sound_seek_position_offset = 18'd1951;
                        8'd10: disk2_sound_seek_position_offset = 18'd2168;
                        8'd11: disk2_sound_seek_position_offset = 18'd2385;
                        8'd12: disk2_sound_seek_position_offset = 18'd2602;
                        8'd13: disk2_sound_seek_position_offset = 18'd2818;
                        8'd14: disk2_sound_seek_position_offset = 18'd3035;
                        8'd15: disk2_sound_seek_position_offset = 18'd3252;
                        8'd16: disk2_sound_seek_position_offset = 18'd3469;
                        8'd17: disk2_sound_seek_position_offset = 18'd3686;
                        8'd18: disk2_sound_seek_position_offset = 18'd3902;
                        8'd19: disk2_sound_seek_position_offset = 18'd4119;
                        8'd20: disk2_sound_seek_position_offset = 18'd4336;
                        8'd21: disk2_sound_seek_position_offset = 18'd4553;
                        8'd22: disk2_sound_seek_position_offset = 18'd4770;
                        8'd23: disk2_sound_seek_position_offset = 18'd4986;
                        8'd24: disk2_sound_seek_position_offset = 18'd5203;
                        8'd25: disk2_sound_seek_position_offset = 18'd5420;
                        8'd26: disk2_sound_seek_position_offset = 18'd5637;
                        8'd27: disk2_sound_seek_position_offset = 18'd5854;
                        8'd28: disk2_sound_seek_position_offset = 18'd6070;
                        8'd29: disk2_sound_seek_position_offset = 18'd6287;
                        8'd30: disk2_sound_seek_position_offset = 18'd6504;
                        8'd31: disk2_sound_seek_position_offset = 18'd6721;
                        8'd32: disk2_sound_seek_position_offset = 18'd6938;
                        8'd33: disk2_sound_seek_position_offset = 18'd7154;
                        8'd34: disk2_sound_seek_position_offset = 18'd7371;
                        8'd35: disk2_sound_seek_position_offset = 18'd7588;
                        8'd36: disk2_sound_seek_position_offset = 18'd7805;
                        8'd37: disk2_sound_seek_position_offset = 18'd8022;
                        8'd38: disk2_sound_seek_position_offset = 18'd8238;
                        8'd39: disk2_sound_seek_position_offset = 18'd8455;
                        8'd40: disk2_sound_seek_position_offset = 18'd8672;
                        8'd41: disk2_sound_seek_position_offset = 18'd8889;
                        8'd42: disk2_sound_seek_position_offset = 18'd9106;
                        8'd43: disk2_sound_seek_position_offset = 18'd9322;
                        8'd44: disk2_sound_seek_position_offset = 18'd9539;
                        8'd45: disk2_sound_seek_position_offset = 18'd9756;
                        8'd46: disk2_sound_seek_position_offset = 18'd9973;
                        8'd47: disk2_sound_seek_position_offset = 18'd10190;
                        8'd48: disk2_sound_seek_position_offset = 18'd10406;
                        8'd49: disk2_sound_seek_position_offset = 18'd10623;
                        8'd50: disk2_sound_seek_position_offset = 18'd10840;
                        8'd51: disk2_sound_seek_position_offset = 18'd11057;
                        8'd52: disk2_sound_seek_position_offset = 18'd11274;
                        8'd53: disk2_sound_seek_position_offset = 18'd11490;
                        8'd54: disk2_sound_seek_position_offset = 18'd11707;
                        8'd55: disk2_sound_seek_position_offset = 18'd11924;
                        8'd56: disk2_sound_seek_position_offset = 18'd12141;
                        8'd57: disk2_sound_seek_position_offset = 18'd12358;
                        8'd58: disk2_sound_seek_position_offset = 18'd12574;
                        8'd59: disk2_sound_seek_position_offset = 18'd12791;
                        8'd60: disk2_sound_seek_position_offset = 18'd13008;
                        8'd61: disk2_sound_seek_position_offset = 18'd13225;
                        8'd62: disk2_sound_seek_position_offset = 18'd13442;
                        8'd63: disk2_sound_seek_position_offset = 18'd13658;
                        8'd64: disk2_sound_seek_position_offset = 18'd13875;
                        8'd65: disk2_sound_seek_position_offset = 18'd14092;
                        8'd66: disk2_sound_seek_position_offset = 18'd14309;
                        8'd67: disk2_sound_seek_position_offset = 18'd14526;
                        8'd68: disk2_sound_seek_position_offset = 18'd14742;
                        8'd69: disk2_sound_seek_position_offset = 18'd14959;
                        8'd70: disk2_sound_seek_position_offset = 18'd15176;
                        8'd71: disk2_sound_seek_position_offset = 18'd15393;
                        8'd72: disk2_sound_seek_position_offset = 18'd15610;
                        8'd73: disk2_sound_seek_position_offset = 18'd15826;
                        8'd74: disk2_sound_seek_position_offset = 18'd16043;
                        8'd75: disk2_sound_seek_position_offset = 18'd16260;
                        8'd76: disk2_sound_seek_position_offset = 18'd16477;
                        8'd77: disk2_sound_seek_position_offset = 18'd16694;
                        8'd78: disk2_sound_seek_position_offset = 18'd16910;
                        8'd79: disk2_sound_seek_position_offset = 18'd17127;
                        8'd80: disk2_sound_seek_position_offset = 18'd17344;
                        8'd81: disk2_sound_seek_position_offset = 18'd17561;
                        8'd82: disk2_sound_seek_position_offset = 18'd17778;
                        8'd83: disk2_sound_seek_position_offset = 18'd17994;
                        8'd84: disk2_sound_seek_position_offset = 18'd18211;
                        8'd85: disk2_sound_seek_position_offset = 18'd18428;
                        8'd86: disk2_sound_seek_position_offset = 18'd18645;
                        8'd87: disk2_sound_seek_position_offset = 18'd18862;
                        8'd88: disk2_sound_seek_position_offset = 18'd19078;
                        8'd89: disk2_sound_seek_position_offset = 18'd19295;
                        8'd90: disk2_sound_seek_position_offset = 18'd19512;
                        8'd91: disk2_sound_seek_position_offset = 18'd19729;
                        8'd92: disk2_sound_seek_position_offset = 18'd19946;
                        8'd93: disk2_sound_seek_position_offset = 18'd20162;
                        8'd94: disk2_sound_seek_position_offset = 18'd20379;
                        8'd95: disk2_sound_seek_position_offset = 18'd20596;
                        8'd96: disk2_sound_seek_position_offset = 18'd20813;
                        8'd97: disk2_sound_seek_position_offset = 18'd21030;
                        8'd98: disk2_sound_seek_position_offset = 18'd21246;
                        8'd99: disk2_sound_seek_position_offset = 18'd21463;
                        8'd100: disk2_sound_seek_position_offset = 18'd21680;
                        8'd101: disk2_sound_seek_position_offset = 18'd21897;
                        8'd102: disk2_sound_seek_position_offset = 18'd22114;
                        8'd103: disk2_sound_seek_position_offset = 18'd22330;
                        8'd104: disk2_sound_seek_position_offset = 18'd22547;
                        8'd105: disk2_sound_seek_position_offset = 18'd22764;
                        8'd106: disk2_sound_seek_position_offset = 18'd22981;
                        8'd107: disk2_sound_seek_position_offset = 18'd23198;
                        8'd108: disk2_sound_seek_position_offset = 18'd23414;
                        8'd109: disk2_sound_seek_position_offset = 18'd23631;
                        8'd110: disk2_sound_seek_position_offset = 18'd23848;
                        8'd111: disk2_sound_seek_position_offset = 18'd24065;
                        8'd112: disk2_sound_seek_position_offset = 18'd24282;
                        8'd113: disk2_sound_seek_position_offset = 18'd24498;
                        8'd114: disk2_sound_seek_position_offset = 18'd24715;
                        8'd115: disk2_sound_seek_position_offset = 18'd24932;
                        8'd116: disk2_sound_seek_position_offset = 18'd25149;
                        8'd117: disk2_sound_seek_position_offset = 18'd25366;
                        8'd118: disk2_sound_seek_position_offset = 18'd25582;
                        8'd119: disk2_sound_seek_position_offset = 18'd25799;
                        8'd120: disk2_sound_seek_position_offset = 18'd26016;
                        8'd121: disk2_sound_seek_position_offset = 18'd26233;
                        8'd122: disk2_sound_seek_position_offset = 18'd26450;
                        8'd123: disk2_sound_seek_position_offset = 18'd26666;
                        8'd124: disk2_sound_seek_position_offset = 18'd26883;
                        8'd125: disk2_sound_seek_position_offset = 18'd27100;
                        8'd126: disk2_sound_seek_position_offset = 18'd27317;
                        8'd127: disk2_sound_seek_position_offset = 18'd27534;
                        8'd128: disk2_sound_seek_position_offset = 18'd27750;
                        8'd129: disk2_sound_seek_position_offset = 18'd27967;
                        8'd130: disk2_sound_seek_position_offset = 18'd28184;
                        8'd131: disk2_sound_seek_position_offset = 18'd28401;
                        8'd132: disk2_sound_seek_position_offset = 18'd28618;
                        8'd133: disk2_sound_seek_position_offset = 18'd28834;
                        8'd134: disk2_sound_seek_position_offset = 18'd29051;
                        8'd135: disk2_sound_seek_position_offset = 18'd29268;
                        8'd136: disk2_sound_seek_position_offset = 18'd29485;
                        8'd137: disk2_sound_seek_position_offset = 18'd29702;
                        8'd138: disk2_sound_seek_position_offset = 18'd29918;
                        8'd139: disk2_sound_seek_position_offset = 18'd30135;
                        8'd140: disk2_sound_seek_position_offset = 18'd30352;
                        default: disk2_sound_seek_position_offset = 18'd30352;
                    endcase
                end
                default: disk2_sound_seek_position_offset = 18'd0;
            endcase
        end
    endfunction

endpackage
