; This file is generated by scripts/build_smartport_rom.py
; Source of truth:
;   - 6502_SSC.CN00.S
;   - 6502_SMARTPORT.S
;   - 6502_SSC.CF00.S
;
; The Appletini SmartPort card uses the reference a2retronet SmartPort
; C800/CF00 flow and the real SSC CN00 slot page for slot 7. The only
; local glue below is for unsupported serial/Pascal entry points, which
; are redirected to RTS because Appletini implements the SmartPort path
; only.

SLOT = 7
SSC = 0


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; APPLE II SSC FIRMWARE         ;
;                               ;
;   BY LARRY KENYON             ;
;                               ;
;    -JANUARY 1981-             ;;;;;;;;;;;;;;
;                                            ;
; (C) COPYRIGHT 1981 BY APPLE COMPUTER, INC. ;
;                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; VARIABLE DEFINITIONS          ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;
; ZERO PAGE EQUS ;
;;;;;;;;;;;;;;;;;;
LOC0 = $00
LOC1 = $01
CH = $24         ; CURSOR HORIZONTAL POSITION
SLOT16 = $26         ; SAVE $N0 TO FREE UP Y-REG
CHARACTER = $27       ; OUTPUT, SCREEN AND INPUT CHARS
BASL = $28         ; BASE SCREEN ADDRESS POINTER
ZPTEMP = $35         ; WORKHORSE TEMPORARY
ZPTMP1 = $2A         ; WHEN ZPTEMP ISN'T ENOUGH
ZPTMP2 = $2B         ; TEMPORARIES, TEMPORARIES!
CSWL = $36         ; CHAR OUT VECTOR
CSWH = $37
KSWL = $38         ; CHAR IN VECTOR
KSWH = $39
A1L = $3C         ; BATCH MOVE POINTER
RNDL = $4E         ; RANDOM NUMBER SEED
RNDH = $4F
;;;;;;;;;;;;;;;;;;;
; GENERAL EQUATES ;
;;;;;;;;;;;;;;;;;;;
STACK = $0100       ; SYSTEM STACK BLOCK
INBUFF = $0200       ; SYSTEM INPUT BUFFER
KBD = $C000       ; KEYBOARD INPUT
KBDSTRB = $C010       ; KEYBOARD CLEAR
ROMSOFF = $CFFF       ; DISABLES C0-RES. $C800 ROMS
;;;;;;;;;;;;;;;;;;;;;;
; SSC CARD ADDRESSES ;
;;;;;;;;;;;;;;;;;;;;;;
DIPSW1 = $C081       ; (+$N0) DIPSWITCH BLOCK 1
DIPSW2 = $C082       ; (+$N0) DIPSWITCH BLOCK 2
TDREG = $C088       ; (+$N0) TRANSMIT DATA REG (WRITE)
RDREG = $C088       ; (+$N0) READ DATA REG (READ)
STREG = $C089       ; (+$N0) STATUS REGISTER (READ)
RESET = $C089       ; (+$N0) SOFTWARE RESET (WRITE)
CMDREG = $C08A       ; (+$N0) COMMAND REGISTER (R/W)
CTLREG = $C08B       ; (+$N0) CONTROL REGISTER (R/W)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;  BIT-> B7  B6  B5  B4  B3  B2  B1  B0
;        +----------------------------+
; DIPSW1 S1  S2  S3  S4  Z   Z   S5  S6  (LEFT DIPSWITCH)
;
; (S1-S4 USED FOR BAUD RATE, S5-S6 FOR FIRMWARE MODE)
;
; DIPSW2 S1  Z   S2  Z   S3  S4  S5  CTS (RIGHT DIPSWITCH)
;
; STREG  INT DSR DCD TDR RDR OVR FE  PE
;
; CTLREG STB << WL >> CK << BAUD RATE >>
;
; CMDREG <<PARITY >> ECH <<XMIT>> RE DTR
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; SCREEN VARIABLES: PPC AND SIC MODES ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CMDBYTE = $5F8-$C0    ; HOLDS COMMAND CHARACTER (PPC & CIC)
HANDSHKE = $4F8-$C0   ; SIC P8A CHAR COUNTER FOR ETX/ACK
PARAMETER = $4F8-$C0  ; ACCUMULATOR FOR CMD PARAMETER
STATEFLG = $578-$C0
; B7=CR GEN ENB FLAG  B6=AFTER LC INPUT FLG
; B2-B0=COMMAND INTERPRETER STATES
;   0 0 0   IDLE
;   0 0 1   CMD CHAR RECEIVED
;   0 1 0   COLLECT <N> UNTIL CHAR THEN DO COMMAND
;   0 1 1   SKIP UNTIL SPACE, THEN GOTO STATE 4
;   1 0 0   E/D COMMANDS
;   1 0 1   UNUSED
;   1 1 0   WAIT UNTIL CR THEN SET STATE TO ZERO
;   1 1 1   WAIT UNTIL CR THEN DO PROC INDICATED BY PARM
;
; (B4-B0 DETERMINE ENQUIRE CHAR FOR P8A MODE)
;
DELAYFLG = $478-$C0
; B7-B6=SCREEN TRANSLATION OPTIONS
;  0 0   LC->UC
;  0 1   NO TRANSLATION
;  1 0   LC->UC INVERSE
;  1 1   LC->UC, UC->UC INVERSE
;  (1-3 WILL ALLOW LC CHARS TO PASS THRU MONITOR)
;
; B5-B4=CR DELAY    0 0 = NO DELAY
; B3-B2=LF DELAY    0 1 = 32 MILLISEC
; B1-BO=FF DELAY    1 0 = 1/4 SEC
;                   1 1 = 2 SEC
;
STSBYTE = $678-$C0    ; STATUS/IORESULT/INPUT BYTE
PWDBYTE = $6F8-$C0    ; PRINTER (FORMAT) WIDTH
COLBYTE = $778-$C0    ; COLUMN POSITION COUNTER
MISCFLG = $7F8-$C0
; B7=ECHO BIT       B6=TABBING OPTION ENABLE
; B5=LINEFEED EAT   B4=PASCAL/BASIC FLAG
; B3=XOFF ENB FLAG  B2=KEYBOARD ENB
; B1=PPC/CIC MODE   B0=LF GENERATE ENB
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; TEMP SCREEN VARS (SLOT INDEPENDENT) ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
MSLOT = $7F8        ; BUFFER FOR HI SLOT ADDR (SCN)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; SCREEN VARIABLES: CIC MODE ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; STATEFLG: B7=TERMINAL MODE FLAG
;        B3-B5=CHAIN SLOT
;
CHNBYTE = $6F8-$C0    ; CURRENT OUTPUT SCREEN ($CN00 ENTRY)
;
; B0-B7=CN00 ENTRY
;
BUFBYTE = $778-$C0    ; BUFFER FOR ONE
;                         INPUT BYTE: HIGH BIT IS SET
;                         WHEN BUFFER IS FULL
;
; MISCFLG: B6=TERM MODE SHIFT ENB
;
; OTHER SLOT VARIABLES AS DEFINED FOR PPC AND SIC MODES
;
;;;;;;;;;;;;;;;;;;;;;;;
; MONITOR SUBROUTINES ;
;;;;;;;;;;;;;;;;;;;;;;;
COUT = $FDED       ; CHARACTER OUT (THRU CSW)
SETKBD = $FE89       ; SETS KSW TO APPLE KEYBOARD
IORTS = $FF58       ; KNOWN "RTS" LOCATION
NXTA1 = $FCBA       ; INCREMENT A1H,L AND CMP TO A2H,L
SETSCR = $FE93       ; SETS CSW TO APPLE SCREEN
VIDOUT = $FDF6       ; OUTPUT A CHAR TO APPLE SCREEN
SLOOP = $FABA       ; CONTINUE SLOT SCAN
SETTXT = $FB39       ; SET TEXT MODE
HOME = $FC58       ; CLEAR SCREEN AND HOME CURSOR
PRERR = $FF2D       ; DISPLAY "ERR" AND BEEP
BASIC = $E000       ; BASIC INTERPRETER COLD START
BASCALC = $FBC1       ; CALC SCREEN BASE ADR IN BASH,L

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; VARIABLE DEFINITIONS          ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;
; ZERO PAGE EQUS ;
;;;;;;;;;;;;;;;;;;
CMD = $42         ; PRODOS COMMAND
UNIT = $43         ; PRODOS UNIT
ADDRL = $44         ; PRODOS / SMARTPORT BUFFER ADDRESS
ADDRH = $45
BLOCKL = $46         ; PRODOS BLOCK
BLOCKH = $47
SIZEL = $46         ; SMARTPORT BUFFER SIZE
SIZEH = $47
;;;;;;;;;;;;;;;;;;;;;;;
; SMARTPORT ADDRESSES ;
;;;;;;;;;;;;;;;;;;;;;;;
DATA = $CFF0       ; SMARTPORT DATA REGISTER
CTRL = $CFF1       ; SMARTPORT CONTROL REGISTER
;;;;;;;;;;;;;;;;;;;;;;;;
; BASIC MODE ADDRESSES ;
;;;;;;;;;;;;;;;;;;;;;;;;
BENTER = $CFF9       ; ENTER A2RETRONET BASIC MODE
BLEAVE = $CFFA       ; LEAVE A2RETRONET BASIC MODE
;;;;;;;;;;;;;;;;;;;;;
; BANKING ADDRESSES ;
;;;;;;;;;;;;;;;;;;;;;
BANKCLR = $CFFB       ; CLEAR EXPANSION ROM BANK
BANKSET = $CFFC       ; SET EXPANSION ROM BANK


; Unsupported SSC serial/Pascal targets are intentionally stubbed.
BINIT = IORTS
PASCALINIT = IORTS
PASCALREAD = IORTS
PASCALWRITE = IORTS
PENTRY = IORTS
SROUT = IORTS
SRIN = IORTS
INIT1 = IORTS
BINPUT = IORTS
OUTPUT = IORTS
CICEXIT = IORTS
SEROUT = IORTS

; Real slot-7 CN00 page from the reference SSC source.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; APPLE II SSC FIRMWARE         ;
;                               ;
;   BY LARRY KENYON             ;
;                               ;
;    -JANUARY 1981-             ;;;;;;;;;;;;;;
;                                            ;
; (C) COPYRIGHT 1981 BY APPLE COMPUTER, INC. ;
;                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; CN00 SPACE CODE               ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        .org $C000+$0100*SLOT


        CMP #$20        ; $CN01:$20
        CMP #$00        ; $CN03:$00
        CMP #$03        ; $CN05:$03
        CMP #$3C        ; $CN07:$3C; ROM builder patches this byte to $00
        CLV
        BVC DENTRY      ; <ALWAYS> SKIP AROUND PASCAL 1.1 ENTRY


        .byte $01         ; GENERIC SIGNATURE BYTE
        .byte $31         ; DEVICE SIGNATURE BYTE
        .byte <PINIT
        .byte <PREAD
        .byte <PWRITE
        .byte <PSTATUS

;;;;;;;;;;;;;;;;;;;
;                 ;
;  BASIC ENTRIES  ;
;                 ;
;;;;;;;;;;;;;;;;;;;

IENTRY: SEC             ; BASIC INPUT ENTRY
        .byte $90         ; OPCODE FOR BCC
OENTRY: CLC             ; BASIC OUTPUT ENTRY
        CLV

BENTRY: STA CHARACTER
        STX ZPTEMP      ; INPUT BUFFER INDEX
        TXA             ; SAVE X AND Y REGS ON STACK
        PHA
        TYA
        PHA
        JSR BSETUP
        JMP BINIT

;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                          ;
;  DISK INTERFACE ENTRIES  ;
;                          ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;

DISK: CLC             ; PRODOS DRIVER ENTRY
        BCC SETUP
        SEC             ; SMARTPORT DRIVER ENTRY
SETUP: JSR DSETUP
        JMP COMMON

DENTRY: JSR DSETUP
        JMP BOOT

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                ;
;      PASCAL INTERFACE ENTRIES  ;
;                                ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
PINIT: JSR PASCALINIT
        LDX #0          ; NO ERROR POSSIBLE
        RTS
PREAD: JMP PASCALREAD
PWRITE: JMP PASCALWRITE
;
; PASCAL STATUS REQUEST
;
; A-REG=0 -> READY FOR OUTPUT?
; A-REG=1 -> HAS INPUT BEEN RECEIVED?
;
PSTATUS: LSR A           ; SAVE REQUEST TYPE IN CARRY
        JSR PENTRY      ; (PRESERVES CARRY)
        BCS PSTATIN
        JSR SROUT       ; READY FOR OUTPUT?
        BEQ PSTATUS2
        CLC
        BCC PSTATUS2    ; CARRY CLEAR EOR NOT READY

PSTATIN: JSR SRIN        ; SETS CARRY CORRECTLY
PSTATUS2: LDA STSBYTE,X  ; GET ERROR FLAGS
        TAX
        RTS

;;;;;;;;;;;;;;;;;;;;;;;;
; SHARED SETUP ROUTINE ;
;;;;;;;;;;;;;;;;;;;;;;;;
BSETUP: LDY #$10*SLOT   ; Y-REG WILL GENERALLY BE $N0
        STY SLOT16
DSETUP: LDX #$C0+SLOT   ; X-REG WILL GENERALLY BE $CN
        STX MSLOT
        STA ROMSOFF     ; SWITCH OUT OTHER $C800 ROMS
        RTS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; ROUTINE TO SEND A CHARACTER TO ANOTHER CARD ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SENDCD: LDX #3
SAVEHOOK: LDA CSWL,x
        PHA
        DEX
        BPL SAVEHOOK
;
; PUT CARD ADDRESS IN HOOK
;
        LDX MSLOT
        LDA CHNBYTE,X
        STA CSWL
        LDA STATEFLG,X  ; GET SLOT #
        AND #$38
        LSR A
        LSR A
        LSR A
        ORA #$C0        ; FORM $CN
        STA CSWH
;
; OUTPUT TO THE PERIPHERAL
;
        LDA CHARACTER
        PHA
        ORA #$80        ; 80 COL BOARDS WANT HI-BIT ON
        JSR COUT
;
; RESTORE EVERYTHING THE OTHER CARD MAY HAVE CLOBBERED
;
        PLA
        STA CHARACTER
        JSR BSETUP
;
; PUT BACK CSWL INTO CHNBYTE
;
        LDA CSWL
        STA CHNBYTE,X

        LDX #0
RESTORHOOK: PLA
        STA CSWL,X
        INX
        CPX #4
        BCC RESTORHOOK

        LDX MSLOT
        RTS

        .res $0100-$10-<*

;;;;;;;;;;;;;;;;;;
;                ;
;  CONFIG ENTRY  ;
;                ;
;;;;;;;;;;;;;;;;;;

CONFIG: JSR DSETUP
        JMP CFG

        .byte $4F, $6C, $53, $63


        .byte $00
        .byte $00         ; SMARTPORT ID
        .byte $00,$00     ; TOTAL BLOCKS
        .byte $D7         ; STATUS BYTE


        .byte <DISK

; Reference SmartPort C800 flow.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                                ;
; MIT License                                                                    ;
;                                                                                ;
; Copyright (c) 2024 Oliver Schmidt (https://a2retro.de/)                        ;
;                                                                                ;
; Permission is hereby granted, free of charge, to any person obtaining a copy   ;
; of this software and associated documentation files (the "Software"), to deal  ;
; in the Software without restriction, including without limitation the rights   ;
; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell      ;
; copies of the Software, and to permit persons to whom the Software is          ;
; furnished to do so, subject to the following conditions:                       ;
;                                                                                ;
; The above copyright notice and this permission notice shall be included in all ;
; copies or substantial portions of the Software.                                ;
;                                                                                ;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR     ;
; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,       ;
; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE    ;
; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER         ;
; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,  ;
; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  ;
; SOFTWARE.                                                                      ;
;                                                                                ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; C800 SPACE                    ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        .org $C800

        .byte $00         ; B/C OF RTS OFFSET

;;;;;;;;;;;;;;;;;;;
; PRODOS COMMANDS ;
;;;;;;;;;;;;;;;;;;;
PDSTS: ; EXECUTE AND GET RETURN CODE
        JSR RETCODE
        BNE PDDONE      ; ERROR?

        LDX DATA        ; SIZE LO
        LDY DATA        ; SIZE HI
PDOKAY: LDA #$00        ; SUCCESS
PDDONE: CMP #$01        ; SUCCESS?
        JMP QUIT

PDRD: ; EXECUTE AND GET RETURN CODE
        JSR RETCODE
        BNE PDDONE      ; ERROR?

        ; READ BLOCK
        JSR RDBLK1
        JMP PDOKAY

PDWR: ; WRITE BLOCK
        JSR WRBLOCK

        ; EXECUTE AND GET RETURN CODE
        JSR RETCODE
        CMP #$01        ; SUCCESS?
        JMP QUIT

;;;;;;;;;;;;;;;;;;;;;;
; SMARTPORT COMMANDS ;
;;;;;;;;;;;;;;;;;;;;;;
STATUS: ; EXECUTE AND GET STATUS
        JSR GETSTS
        BNE RETURN      ; ERROR?

        ; READ STATUS LIST SIZE
        LDA DATA
        STA SIZEL
        LDA DATA
        STA SIZEH

        ; READ STATUS LIST
        LDY #$02        ; OFFSET OF STATUS LIST ADDRESS
        JSR SETADDR
        JSR RDBUF
        LDX SIZEL
        LDY SIZEH
        JMP RETURN

READBL: ; EXECUTE AND GET STATUS
        JSR GETSTS
        BNE RETURN      ; ERROR?

        ; READ BLOCK
        LDY #$02        ; OFFSET OF BUFFER ADDRESS
        JSR SETADDR
        JSR RDBLK1
        JMP RETURN

WRITEBL: ; WRITE BLOCK
        LDY #$02        ; OFFSET OF BUFFER ADDRESS
        JSR SETADDR
        JSR WRBLOCK
        ; FALL THROUGH

FORMAT: ; EXECUTE AND GET STATUS
        JSR GETSTS
        JMP RETURN

CONTROL: ; WRITE CONTROL LIST
        LDY #$02        ; OFFSET OF CONTROL LIST ADDRSS
        JSR SETADDR
        LDY #$00        ; OFFSET OF CONTROL LIST SIZE
        JSR SETSIZE
        LDA SIZEL
        CLC
        ADC #$02        ; ADD SIZE OF CONTROL LIST SIZE
        STA SIZEL
        BCC NOINC
        INC SIZEH
NOINC: JSR WRBUF
        ; FALL THROUGH

INIT: ; FALL THROUGH

OPEN: ; FALL THROUGH

CLOSE: ; EXECUTE AND GET STATUS
        JSR GETSTS
        JMP RETURN

READ: ; EXECUTE AND GET STATUS
        JSR GETSTS
        BNE RETURN      ; ERROR?

        ; READ BUFFER
        LDY #$04        ; OFFSET OF BYTE COUNT
        JSR SETSIZE
        LDY #$02        ; OFFSET OF BUFFER ADDRESS
        JSR SETADDR
        JSR RDBUF
        JMP RETURN

WRITE: ; WRITE BUFFER
        LDY #$04        ; OFFSET OF BYTE COUNT
        JSR SETSIZE
        LDY #$02        ; OFFSET OF BUFFER ADDRESS
        JSR SETADDR
        JSR WRBUF

        ; EXECUTE AND GET STATUS
        JSR GETSTS
        ; FALL THROUGH

RETURN: ; RESTORE ZEROPAGE LOCATIONS
        PLA
        STA ADDRL
        PLA
        STA ADDRH
        PLA
        STA SIZEL
        PLA
        STA SIZEH
        PLA             ; STATUS
        CMP #$01        ; SET CARRY
        JMP QUIT

;;;;;;;;;;;;;;;;;;
; HANDLER SWITCH ;
;;;;;;;;;;;;;;;;;;
SWITCH: BCC PRODOS
        JMP SMARTPORT

;;;;;;;;;;;;;;;;;;
; PRODOS HANDLER ;
;;;;;;;;;;;;;;;;;;
PRODOS: ; WRITE PARAMETERS
        LDX CMD
        STX DATA
        LDA UNIT
        STA DATA
        LDA ADDRL
        STA DATA
        LDA ADDRH
        STA DATA
        LDA BLOCKL
        STA DATA
        LDA BLOCKH
        STA DATA

        ; DISPATCH COMMAND
        LDA #>$C800
        PHA
        LDA PDCMD,X
        PHA
        RTS

PDCMD: .byte <PDSTS-1, <PDRD-1, <PDWR-1

;;;;;;;;;;;;;;;;;;;;;
; SMARTPORT HANDLER ;
;;;;;;;;;;;;;;;;;;;;;
SMARTPORT:
        ; SAVE ZEROPAGE LOCATIONS AND RESERVE STATUS SLOT
        TSX
        LDY #$04
SAVE: LDA ADDRL,Y
        PHA
        DEY
        BPL SAVE

        ; GET ADDRESS OF PARAMETERS AND ADJUST STACK
        CLC
        INX
        LDA $0100,X
        STA ADDRL
        ADC #<$0003     ; SIZE OF PARAMETERS
        STA $0100,X
        INX
        LDA $0100,X
        STA ADDRH
        ADC #>$0003     ; SIZE OF PARAMETERS
        STA $0100,X

        ; PREPARE COMMAND DISPATCH
        LDA #>$C800
        PHA
        LDY #$01+$00    ; PUSH OFFSET + OFFSET OF COMMAND NUMBER
        LDA (ADDRL),Y
        TAX
        LDA SPCMD,X
        PHA

        ; WRITE COMMAND NUMBER
        STX DATA

        ; GET COMMAND LIST ADDRESS
        LDY #$01+$01    ; PUSH OFFSET + OFFSET OF COMMAND LIST ADDRESS
        JSR SETADDR

        ; WRITE COMMAND LIST
        LDA #<$0009     ; SIZE OF LARGEST COMMAND LIST
        STA SIZEL
        LDA #>$0009     ; SIZE OF LARGEST COMMAND LIST
        STA SIZEH
        JSR WRBUF

        ; DISPATCH COMMAND
        RTS

SPCMD: .byte <STATUS-1, <READBL-1, <WRITEBL-1, <FORMAT-1, <CONTROL-1
        .byte <INIT  -1, <OPEN  -1, <CLOSE  -1, <READ  -1, <WRITE  -1

;;;;;;;;;
; UTILS ;
;;;;;;;;;
SETSIZE: ; SET 16-BIT BUFFER SIZE
        LDA (ADDRL),Y
        STA SIZEL
        INY
        LDA (ADDRL),Y
        STA SIZEH
        RTS

SETADDR: ; SET BUFFER ADDRESS
        LDA (ADDRL),Y
        TAX
        INY
        LDA (ADDRL),Y
        STA ADDRH
        STX ADDRL
        RTS

GETSTS: ; EXECUTE SMARTPORT COMMAND AND GET STATUS
        LDA #$02        ; SMARTPORT
        JSR WRCMD

        ; SAVE STATUS IN STACK SLOT
        TSX
        TAY
        TXA
        CLC
        ADC #$07        ; OFFSET OF STACK SLOT
        TAX
        TYA
        STA $0100,X
        RTS

RETCODE: ; EXECUTE PRODOS COMMAND AND GET RETURN CODE
        LDA #$01        ; PRODOS
        ; FALL THROUGH

WRCMD: ; WRITE COMMAND REG AND READ RESPONSE
        STA CTRL
WAIT: LDA CTRL
        BPL WAIT
        LDA DATA
        RTS

RDBUF: ; READ BUFFER
        LDY #$00
        LDX SIZEH
        BEQ RDREST
RDFULL: JSR RDPAGE
        INC ADDRH
        DEX
        BNE RDFULL
RDREST: LDX SIZEL
        BEQ RDDONE
RDMORE: LDA DATA
        STA (ADDRL),Y
        INY
        DEX
        BNE RDMORE
RDDONE: RTS

WRBUF: ; WRITE BUFFER
        LDY #$00
        LDX SIZEH
        BEQ WRREST
WRFULL: JSR WRPAGE
        INC ADDRH
        DEX
        BNE WRFULL
WRREST: LDX SIZEL
        BEQ WRDONE
WRMORE: LDA (ADDRL),Y
        STA DATA
        INY
        DEX
        BNE WRMORE
WRDONE: RTS

RDBLK1: ; READ 512-BYTE BLOCK (in-bank; CF00 RDBLOCK jumps here)
        LDY #$00
        JSR RDPAGE
        INC ADDRH
        JSR RDPAGE
        DEC ADDRH
        RTS
RDPAGE: LDA DATA
        STA (ADDRL),Y
        INY
        BNE RDPAGE
        RTS

WRBLOCK: ; WRITE 512-BYTE BLOCK
        LDY #$00
        JSR WRPAGE
        INC ADDRH
        JSR WRPAGE
        DEC ADDRH
        RTS
WRPAGE: LDA (ADDRL),Y
        STA DATA
        INY
        BNE WRPAGE
        RTS

;;;;;;;;;;;;;;;;
; BOOT HANDLER ;
;;;;;;;;;;;;;;;;
BOOT1: LDX #$FF
RETRY: LDA KBD
        BMI HAVEKEY
        INX
        STX DATA
        LDA #$40        ; CONFIG
        JSR WRCMD
        BNE DOBOOT
        LDA DATA
        STA $07F7
        BNE RETRY       ; ALWAYS
HAVEKEY: STA KBDSTRB
        CLV             ; NO ERROR TEXT
        CMP #'C'+$80
        BEQ DOCFG
        CMP #'c'+$80
        BEQ DOCFG
        CMP #'N'+$80
        BEQ DONE
        CMP #'n'+$80
        BEQ DONE
        CMP #'1'+$80
        BCC DOBOOT
        CMP #'9'+$80
        BCS DOBOOT
        LDY #$64        ; SET BOOT
        STY DATA
        STA DATA
        LDA #$40        ; CONFIG
        JSR WRCMD
        BEQ DOBOOT
        BNE RETRY       ; ALWAYS

DOCFG: JSR CFGHDLR

DOBOOT: LDX #$01
        STX CMD
        LDA MSLOT
        ASL
        ASL
        ASL
        ASL
        STA UNIT        ; DRIVE 1
        DEX
        STX ADDRL
        LDA #>$0800
        STA ADDRH
        STX BLOCKL
        STX BLOCKH
        JMP PDBOOT      ; CALL PRODOS HANDLER

BOOT2: BIT ERRTEXT     ; "SEV" -> ERROR TEXT
        BCS DONE
        LDX $0800       ; NUMBER OF DISK II SECTORS TO READ
        DEX
        BNE DONE        ; ... MUST BE 1
        LDA $0801       ; FIRST OPCODE
        BEQ DONE        ; ... MUSTN'T BE BRK
        LDA #>($0801-1)
        PHA
        LDA #<($0801-1)
        PHA
        LDX UNIT
        JMP QUIT        ; GO FOR IT

DONE: LDA LOC0        ; POTENTIAL AUTOSTART SCAN ROM PTR LO
        BNE EXIT        ; ... MUST POINT TO A SLOT ROM START
        LDA LOC1        ; POTENTIAL AUTOSTART SCAN ROM PTR HI
        CMP MSLOT
        BNE EXIT        ; ... MUST POINT TO CURRENT SLOT ROM
        LDA #>(SLOOP-1)
        PHA
        LDA #<(SLOOP-1)
        PHA
        JMP QUIT        ; LOOKS LIKE AUTOSTART SCAN SO CONTINUE SCAN

EXIT: PHP             ; SAVE V
        JSR SETSCR
        JSR SETKBD
        JSR SETTXT
        JSR HOME
        PLP             ; RESTORE V
        BVC COLD
        LDX #$08        ; 'HDD ERROR'
ERR: LDA ERRTEXT,X
        JSR COUT
        DEX
        BPL ERR
COLD: LDA #>(BASIC-1)
        PHA
        LDA #<(BASIC-1)
        PHA
        JMP QUIT

ERRTEXT: .byte 'R'|$80, 'O'|$80, 'R'|$80, 'R'|$80, 'E'|$80, ' '|$80, 'D'|$80, 'D'|$80, 'H'|$80

;;;;;;;;;;;;;;;;;;
; CONFIG HANDLER ;
;;;;;;;;;;;;;;;;;;
CFGHDLR: STA $C051       ; TEXT
        STA $C054       ; PAGE 1
        LDA $FBB3
        CMP #$38        ; APPLE ][
        BEQ UPPER
        CMP #$EA        ; APPLE ][+
        BEQ UPPER
        LDA $FBC0
        CMP #$EA        ; APPLE //e
        BEQ UPPER
        LDA $C01E       ; CHARSET?
        PHA
        STA $C00F       ; ALT CHARSET
        LDA $C01F       ; COLS?
        PHA
        STA $C00C       ; 40 COLS
        LDA #$66        ; LOWERCASE
        PHP
        BNE LOOP        ; ALWAYS
UPPER: PHP
        LDA #$65        ; UPPERCASE

LOOP: STA DATA
        LDA #$40        ; CONFIG
        JSR WRCMD
        BNE SCRN        ; QUIT?

        PLP
        BEQ NOCHAR
        PLA             ; COLS
        BPL NOCOLS      ; 40 COLS?
        STA $C00D       ; 80 COLS
NOCOLS: PLA             ; CHARSET
        BMI NOCHAR      ; ALT CHARSET?
        STA $C00E       ; PRI CHARSET
NOCHAR: JSR HOME
        RTS

SCRN: LDX #$00
LINE: TXA
        JSR BASCALC
        LDY #$00
CHAR: LDA DATA
        STA (BASL),Y
        INY
        CPY #$28        ; COLS
        BCC CHAR
        INX
        CPX #$18        ; ROWS
        BCC LINE

GETKEY: LDA KBD
        BPL GETKEY
        STA KBDSTRB
        BMI LOOP

        .res $CF00-*

; Reference CF00 common page.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; APPLE II SSC FIRMWARE         ;
;                               ;
;   BY LARRY KENYON             ;
;                               ;
;    -JANUARY 1981-             ;;;;;;;;;;;;;;
;                                            ;
; (C) COPYRIGHT 1981 BY APPLE COMPUTER, INC. ;
;                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; CF00 SPACE                    ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        .org $CF00

;;;;;;;;
; BOOT ;
;;;;;;;;
BOOT: LDA #$01        ; SMARTPORT FIRMWARE
        STA BANKSET
        JMP BOOT1

PDBOOT: JSR PRODOS
        LDA #$01        ; SMARTPORT FIRMWARE
        STA BANKSET
        JMP BOOT2

;;;;;;;;;;;;;;;;;;
; COMMON HANDLER ;
;;;;;;;;;;;;;;;;;;
COMMON: LDA #$01        ; SMARTPORT FIRMWARE
        STA BANKSET
        JMP SWITCH

;;;;;;;;;;;;;;;
; COMMON QUIT ;
;;;;;;;;;;;;;;;
QUIT: STA BANKCLR
        RTS

;;;;;;;;;;;;;;;;;;;;;;;
; READ 512-BYTE BLOCK ;
;;;;;;;;;;;;;;;;;;;;;;;

RDBLOCK: JMP RDBLK1      ; Appletini has an unbanked C8 image so the
                        ; (the a2retronet bank-2/3 page stubs do not
                        ; exist here; BANKSET writes are ignored ROM
                        ; space on this card)

;;;;;;;;;;
; CONFIG ;
;;;;;;;;;;
CFG: LDA #$01        ; SMARTPORT FIRMWARE
        STA BANKSET
        JSR CFGHDLR
        STA BANKCLR
        RTS

;;;;;;;;;;;;;;;;;;;;;;;;
; BASIC INITIALIZATION ;
;;;;;;;;;;;;;;;;;;;;;;;;
BINIT: STA BENTER      ; ENTER A2RETRONET BASIC MODE
        BVC NORMIO
        ASL CMDBYTE,X   ; ALWAYS ENABLE COMMANDS
        LSR CMDBYTE,X
        LDA CMDREG,Y    ; JUST HAD A POWER-ON OR PROGRAM RESET?
        AND #$1F
        BNE BINIT1
        LDA #$EF        ; IF SO, GO JOIN INIT IN PROGRESS
        JSR INIT1

BINIT1: CPX CSWH
        BNE FROMIN
        LDA #<OENTRY
        CMP CSWL        ; IF CSW IS ALREADY POINTING TO OENTRY,
        BEQ FROMIN      ;  THEN WE MUST HAVE COME FROM KSW
        STA CSWL        ; OTHERWISE, SET CSW TO OENTRY
FROMOUT: CLC             ; INDICATE WE ARE CALLED FOR OUTPUT
        BCC NORMIO      ; <ALWAYS>
FROMIN: CPX KSWH        ; MAKE SURE KSW POINTS HERE
        BNE FROMOUT     ;
        LDA #<IENTRY
        STA KSWL        ; SET UP KSW (NOTE CARRY SET FROM CPX)
;
; BRANCH TO APPROPRIATE BASIC I/O ROUTINE
;
NORMIO: LDA MISCFLG,X   ; SEPARATE CIC MODE FROM OTHERS
        AND #$02        ; NOT ZERO FOR CIC MODE
        PHP             ; SAVE CIC MODE INDICATION
        BCC BOUTPUT
        JMP BINPUT

BOUTPUT: LDA STATEFLG,X  ; CHECK FOR AFTER LOWERCASE INPUT
        PHA
        ASL A
        BPL BOUTPUT1    ; SKIP IF NOT
        LDX ZPTEMP
        LDA CHARACTER
        ORA #$20
        STA INBUFF,X    ; RESTORE LOWERCASE IN BUFFER
        STA CHARACTER   ; AND FOR OUTPUT ECHO
        LDX MSLOT
BOUTPUT1: PLA
        AND #$BF        ; ZERO THE FLAG
        STA STATEFLG,X
        PLP             ; RETRIEVE CIC MODE INDICATION
        BEQ BOUTPUT2    ; BRANCH FOR PPC, SIC MODES
        JSR OUTPUT      ; CIC MODE OUTPUT
        JMP CICEXIT     ; FINISH BY CHECKING FOR TERM MODE

BOUTPUT2: JMP SEROUT

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; RETURN FROM BASIC ENTRIES ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
BEXIT: LDA CHARACTER
        STA BLEAVE      ; LEAVE A2RETRONET BASIC MODE
        RTS

        .res $D000-*
