; This file is generated by scripts/build_ssc_rom.py
; Source of truth:
;   - 6502_SSC.CN00.S
;   - 6502_SSC.C800.S / .HILEV.S / .TERM.S / .CORE.S / .UTIL.S / .CMD.S
;   - 6502_SSC.CF00.S (a2retronet banked entries stubbed to RTS)
;
; Slot-1 SSC build: the full Apple serial firmware, one unbanked image.

SLOT = 1
SSC = 1


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; APPLE II SSC FIRMWARE         ;
;                               ;
;   BY LARRY KENYON             ;
;                               ;
;    -JANUARY 1981-             ;;;;;;;;;;;;;;
;                                            ;
; (C) COPYRIGHT 1981 BY APPLE COMPUTER, INC. ;
;                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; VARIABLE DEFINITIONS          ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;
; ZERO PAGE EQUS ;
;;;;;;;;;;;;;;;;;;
LOC0 = $00
LOC1 = $01
CH = $24         ; CURSOR HORIZONTAL POSITION
SLOT16 = $26         ; SAVE $N0 TO FREE UP Y-REG
CHARACTER = $27       ; OUTPUT, SCREEN AND INPUT CHARS
BASL = $28         ; BASE SCREEN ADDRESS POINTER
ZPTEMP = $35         ; WORKHORSE TEMPORARY
ZPTMP1 = $2A         ; WHEN ZPTEMP ISN'T ENOUGH
ZPTMP2 = $2B         ; TEMPORARIES, TEMPORARIES!
CSWL = $36         ; CHAR OUT VECTOR
CSWH = $37
KSWL = $38         ; CHAR IN VECTOR
KSWH = $39
A1L = $3C         ; BATCH MOVE POINTER
RNDL = $4E         ; RANDOM NUMBER SEED
RNDH = $4F
;;;;;;;;;;;;;;;;;;;
; GENERAL EQUATES ;
;;;;;;;;;;;;;;;;;;;
STACK = $0100       ; SYSTEM STACK BLOCK
INBUFF = $0200       ; SYSTEM INPUT BUFFER
KBD = $C000       ; KEYBOARD INPUT
KBDSTRB = $C010       ; KEYBOARD CLEAR
ROMSOFF = $CFFF       ; DISABLES C0-RES. $C800 ROMS
;;;;;;;;;;;;;;;;;;;;;;
; SSC CARD ADDRESSES ;
;;;;;;;;;;;;;;;;;;;;;;
DIPSW1 = $C081       ; (+$N0) DIPSWITCH BLOCK 1
DIPSW2 = $C082       ; (+$N0) DIPSWITCH BLOCK 2
TDREG = $C088       ; (+$N0) TRANSMIT DATA REG (WRITE)
RDREG = $C088       ; (+$N0) READ DATA REG (READ)
STREG = $C089       ; (+$N0) STATUS REGISTER (READ)
RESET = $C089       ; (+$N0) SOFTWARE RESET (WRITE)
CMDREG = $C08A       ; (+$N0) COMMAND REGISTER (R/W)
CTLREG = $C08B       ; (+$N0) CONTROL REGISTER (R/W)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;  BIT-> B7  B6  B5  B4  B3  B2  B1  B0
;        +----------------------------+
; DIPSW1 S1  S2  S3  S4  Z   Z   S5  S6  (LEFT DIPSWITCH)
;
; (S1-S4 USED FOR BAUD RATE, S5-S6 FOR FIRMWARE MODE)
;
; DIPSW2 S1  Z   S2  Z   S3  S4  S5  CTS (RIGHT DIPSWITCH)
;
; STREG  INT DSR DCD TDR RDR OVR FE  PE
;
; CTLREG STB << WL >> CK << BAUD RATE >>
;
; CMDREG <<PARITY >> ECH <<XMIT>> RE DTR
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; SCREEN VARIABLES: PPC AND SIC MODES ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CMDBYTE = $5F8-$C0    ; HOLDS COMMAND CHARACTER (PPC & CIC)
HANDSHKE = $4F8-$C0   ; SIC P8A CHAR COUNTER FOR ETX/ACK
PARAMETER = $4F8-$C0  ; ACCUMULATOR FOR CMD PARAMETER
STATEFLG = $578-$C0
; B7=CR GEN ENB FLAG  B6=AFTER LC INPUT FLG
; B2-B0=COMMAND INTERPRETER STATES
;   0 0 0   IDLE
;   0 0 1   CMD CHAR RECEIVED
;   0 1 0   COLLECT <N> UNTIL CHAR THEN DO COMMAND
;   0 1 1   SKIP UNTIL SPACE, THEN GOTO STATE 4
;   1 0 0   E/D COMMANDS
;   1 0 1   UNUSED
;   1 1 0   WAIT UNTIL CR THEN SET STATE TO ZERO
;   1 1 1   WAIT UNTIL CR THEN DO PROC INDICATED BY PARM
;
; (B4-B0 DETERMINE ENQUIRE CHAR FOR P8A MODE)
;
DELAYFLG = $478-$C0
; B7-B6=SCREEN TRANSLATION OPTIONS
;  0 0   LC->UC
;  0 1   NO TRANSLATION
;  1 0   LC->UC INVERSE
;  1 1   LC->UC, UC->UC INVERSE
;  (1-3 WILL ALLOW LC CHARS TO PASS THRU MONITOR)
;
; B5-B4=CR DELAY    0 0 = NO DELAY
; B3-B2=LF DELAY    0 1 = 32 MILLISEC
; B1-BO=FF DELAY    1 0 = 1/4 SEC
;                   1 1 = 2 SEC
;
STSBYTE = $678-$C0    ; STATUS/IORESULT/INPUT BYTE
PWDBYTE = $6F8-$C0    ; PRINTER (FORMAT) WIDTH
COLBYTE = $778-$C0    ; COLUMN POSITION COUNTER
MISCFLG = $7F8-$C0
; B7=ECHO BIT       B6=TABBING OPTION ENABLE
; B5=LINEFEED EAT   B4=PASCAL/BASIC FLAG
; B3=XOFF ENB FLAG  B2=KEYBOARD ENB
; B1=PPC/CIC MODE   B0=LF GENERATE ENB
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; TEMP SCREEN VARS (SLOT INDEPENDENT) ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
MSLOT = $7F8        ; BUFFER FOR HI SLOT ADDR (SCN)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; SCREEN VARIABLES: CIC MODE ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; STATEFLG: B7=TERMINAL MODE FLAG
;        B3-B5=CHAIN SLOT
;
CHNBYTE = $6F8-$C0    ; CURRENT OUTPUT SCREEN ($CN00 ENTRY)
;
; B0-B7=CN00 ENTRY
;
BUFBYTE = $778-$C0    ; BUFFER FOR ONE
;                         INPUT BYTE: HIGH BIT IS SET
;                         WHEN BUFFER IS FULL
;
; MISCFLG: B6=TERM MODE SHIFT ENB
;
; OTHER SLOT VARIABLES AS DEFINED FOR PPC AND SIC MODES
;
;;;;;;;;;;;;;;;;;;;;;;;
; MONITOR SUBROUTINES ;
;;;;;;;;;;;;;;;;;;;;;;;
COUT = $FDED       ; CHARACTER OUT (THRU CSW)
SETKBD = $FE89       ; SETS KSW TO APPLE KEYBOARD
IORTS = $FF58       ; KNOWN "RTS" LOCATION
NXTA1 = $FCBA       ; INCREMENT A1H,L AND CMP TO A2H,L
SETSCR = $FE93       ; SETS CSW TO APPLE SCREEN
VIDOUT = $FDF6       ; OUTPUT A CHAR TO APPLE SCREEN
SLOOP = $FABA       ; CONTINUE SLOT SCAN
SETTXT = $FB39       ; SET TEXT MODE
HOME = $FC58       ; CLEAR SCREEN AND HOME CURSOR
PRERR = $FF2D       ; DISPLAY "ERR" AND BEEP
BASIC = $E000       ; BASIC INTERPRETER COLD START
BASCALC = $FBC1       ; CALC SCREEN BASE ADR IN BASH,L

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; VARIABLE DEFINITIONS          ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;
; ZERO PAGE EQUS ;
;;;;;;;;;;;;;;;;;;
CMD = $42         ; PRODOS COMMAND
UNIT = $43         ; PRODOS UNIT
ADDRL = $44         ; PRODOS / SMARTPORT BUFFER ADDRESS
ADDRH = $45
BLOCKL = $46         ; PRODOS BLOCK
BLOCKH = $47
SIZEL = $46         ; SMARTPORT BUFFER SIZE
SIZEH = $47
;;;;;;;;;;;;;;;;;;;;;;;
; SMARTPORT ADDRESSES ;
;;;;;;;;;;;;;;;;;;;;;;;
DATA = $CFF0       ; SMARTPORT DATA REGISTER
CTRL = $CFF1       ; SMARTPORT CONTROL REGISTER
DPOP = $CFF2       ; SMARTPORT POP REGISTER (WRITE-ONLY, VALUE IGNORED)
;;;;;;;;;;;;;;;;;;;;;;;;
; BASIC MODE ADDRESSES ;
;;;;;;;;;;;;;;;;;;;;;;;;
BENTER = $CFF9       ; ENTER A2RETRONET BASIC MODE
BLEAVE = $CFFA       ; LEAVE A2RETRONET BASIC MODE
;;;;;;;;;;;;;;;;;;;;;
; BANKING ADDRESSES ;
;;;;;;;;;;;;;;;;;;;;;
BANKCLR = $CFFB       ; CLEAR EXPANSION ROM BANK
BANKSET = $CFFC       ; SET EXPANSION ROM BANK


; Slot page ($C100).

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; APPLE II SSC FIRMWARE         ;
;                               ;
;   BY LARRY KENYON             ;
;                               ;
;    -JANUARY 1981-             ;;;;;;;;;;;;;;
;                                            ;
; (C) COPYRIGHT 1981 BY APPLE COMPUTER, INC. ;
;                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; CN00 SPACE CODE               ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        .org $C000+$0100*SLOT


        BIT IORTS       ; SET THE V-FLAG
        BVS BENTRY      ; <ALWAYS>
        SEC
        .byte $90         ; OPCODE FOR BCC
        CLC
        CLV
        BVC BENTRY      ; <ALWAYS> SKIP AROUND PASCAL 1.1 ENTRY


        .byte $01         ; GENERIC SIGNATURE BYTE
        .byte $31         ; DEVICE SIGNATURE BYTE
        .byte <PINIT
        .byte <PREAD
        .byte <PWRITE
        .byte <PSTATUS

;;;;;;;;;;;;;;;;;;;
;                 ;
;  BASIC ENTRIES  ;
;                 ;
;;;;;;;;;;;;;;;;;;;

IENTRY: SEC             ; BASIC INPUT ENTRY
        .byte $90         ; OPCODE FOR BCC
OENTRY: CLC             ; BASIC OUTPUT ENTRY
        CLV

BENTRY: STA CHARACTER
        STX ZPTEMP      ; INPUT BUFFER INDEX
        TXA             ; SAVE X AND Y REGS ON STACK
        PHA
        TYA
        PHA
        JSR BSETUP
        JMP BINIT

;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                          ;
;  DISK INTERFACE ENTRIES  ;
;                          ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;

DISK: CLC             ; PRODOS DRIVER ENTRY
        BCC SETUP
        SEC             ; SMARTPORT DRIVER ENTRY
SETUP: JSR DSETUP
        JMP COMMON

DENTRY: JSR DSETUP
        JMP BOOT

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                ;
;  NEW PASCAL INTERFACE ENTRIES  ;
;                                ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
PINIT: JSR PASCALINIT
        LDX #0          ; NO ERROR POSSIBLE
        RTS
PREAD: JMP PASCALREAD
PWRITE: JMP PASCALWRITE
;
; NEW PASCAL STATUS REQUEST
;
; A-REG=0 -> READY FOR OUTPUT?
; A-REG=1 -> HAS INPUT BEEN RECEIVED?
;
PSTATUS: LSR A           ; SAVE REQUEST TYPE IN CARRY
        JSR PENTRY      ; (PRESERVES CARRY)
        BCS PSTATIN
        JSR SROUT       ; READY FOR OUTPUT?
        BEQ PSTATUS2
        CLC
        BCC PSTATUS2    ; CARRY CLEAR EOR NOT READY

PSTATIN: JSR SRIN        ; SETS CARRY CORRECTLY
PSTATUS2: LDA STSBYTE,X  ; GET ERROR FLAGS
        TAX
        RTS

;;;;;;;;;;;;;;;;;;;;;;;;
; SHARED SETUP ROUTINE ;
;;;;;;;;;;;;;;;;;;;;;;;;
BSETUP: LDY #$10*SLOT   ; Y-REG WILL GENERALLY BE $N0
        STY SLOT16
DSETUP: LDX #$C0+SLOT   ; X-REG WILL GENERALLY BE $CN
        STX MSLOT
        STA ROMSOFF     ; SWITCH OUT OTHER $C800 ROMS
        RTS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; ROUTINE TO SEND A CHARACTER TO ANOTHER CARD ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SENDCD: LDX #3
SAVEHOOK: LDA CSWL,x
        PHA
        DEX
        BPL SAVEHOOK
;
; PUT CARD ADDRESS IN HOOK
;
        LDX MSLOT
        LDA CHNBYTE,X
        STA CSWL
        LDA STATEFLG,X  ; GET SLOT #
        AND #$38
        LSR A
        LSR A
        LSR A
        ORA #$C0        ; FORM $CN
        STA CSWH
;
; OUTPUT TO THE PERIPHERAL
;
        LDA CHARACTER
        PHA
        ORA #$80        ; 80 COL BOARDS WANT HI-BIT ON
        JSR COUT
;
; RESTORE EVERYTHING THE OTHER CARD MAY HAVE CLOBBERED
;
        PLA
        STA CHARACTER
        JSR BSETUP
;
; PUT BACK CSWL INTO CHNBYTE
;
        LDA CSWL
        STA CHNBYTE,X

        LDX #0
RESTORHOOK: PLA
        STA CSWL,X
        INX
        CPX #4
        BCC RESTORHOOK

        LDX MSLOT
        RTS

        .res $0100-$10-<*

;;;;;;;;;;;;;;;;;;
;                ;
;  CONFIG ENTRY  ;
;                ;
;;;;;;;;;;;;;;;;;;

CONFIG: JSR DSETUP
        JMP CFG

        .byte $4F, $6C, $53, $63


        .byte $41, $50, $50, $4C, $45


        .byte <DISK

; C800 high level.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; APPLE II SSC FIRMWARE         ;
;                               ;
;   BY LARRY KENYON             ;
;                               ;
;    -JANUARY 1981-             ;;;;;;;;;;;;;;
;                                            ;
; (C) COPYRIGHT 1981 BY APPLE COMPUTER, INC. ;
;                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; C800 SPACE: HIGH LEVEL STUFF  ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; PASCAL 1.0 INIT ENTRY ;
;;;;;;;;;;;;;;;;;;;;;;;;;

        .org $C800

PASCALINIT: JSR PENTRY   ; PASCAL 1.0 INITIALIZATION ENTRY
        LDA #$16        ; NO XOFF, ECHO, LF EAT, OR LF GEN
INIT1: PHA             ; GOES TO MISCFLG AFTER MODIFICATION
        LDA #0
        STA STATEFLG,X
        STA DELAYFLG,X
        STA HANDSHKE,X
        STA STSBYTE,X
        STA PWDBYTE,X
        STA COLBYTE,X
        LDA DIPSW2,Y    ; SET LF GEN OPTION FROM D2-S5
        STA ZPTMP2      ; SAVE FOR LATER
        LSR A           ; S5-> CARRY
        LSR A           ; IF S5=ON=0 THEN LEAVE MISCFLG ALONE
        BCC INIT1A
        PLA             ; OTHERWISE, MAKE SURE LF GEN
        AND #$FE        ;  ENABLE IS RESET
        PHA
INIT1A: CLV             ; V WILL BE CLEAR FOR CIC MODE
        LDA DIPSW1,Y
        LSR A           ; SIC MODES SET CARRY
        BCS INIT2       ; BRANCH FOR SIC MODES
        LSR A
        BCS INIT2B      ; PPC MODE BRANCH
        LDA #$01        ; CTL-A
        BNE INIT5       ; <ALWAYS> CIC MODE BRANCH

INIT2: LSR A           ; SET CARRY FOR P8A
        LDA #$03        ; SET ETX AS DEFAULT INQUIRY CHAR
        BCS INIT2A      ; BRANCH FOR P8A
        LDA #$80        ; FOR P8 SET AUTO CR GEN
INIT2A: STA STATEFLG,X
INIT2B: BIT IORTS       ; SET V-FLAG FOR PPC, SIC MODES
        LDA ZPTMP2
        AND #$20        ; SET CR DELAY
        EOR #$20        ; SO 1=ENB, 0=DISABLE
        STA DELAYFLG,X  ; FROM D2-S2

        BVS INIT3       ; <ALWAYS> BRANCH AROUND PASCAL
;;;;;;;;;;;;;;;;;;;;;;;;;
; PASCAL 1.0 READ ENTRY ;
; (MUST BE AT $C84D)    ;
;;;;;;;;;;;;;;;;;;;;;;;;;
PREAD0: JSR PASCALREAD  ; DO PASCAL 1.1 READ
        LDX MSLOT       ; MODIFY FOR 1.0
        STA STSBYTE,X   ; CHARACTER READ
        RTS
;;;;;;;;;;;;;;;;;;;;;;;;
; NOW WHERE WERE WE??? ;
;;;;;;;;;;;;;;;;;;;;;;;;

INIT3: LDA ZPTMP2      ; PPC, SIC MODES USE SWITCHES
        LSR A           ; TO SET PWIDTH, CR DELAY
        LSR A
        AND #$03
        TAY
        BEQ INIT4

        PLA             ; RESET VIDEO ENABLE FOR PWIDTH#40
        AND #$7F
        PHA

INIT4: LDA PWDTBL,Y
        STA PWDBYTE,X
        LDY SLOT16

        PLA             ; CLEAR CIC BIT IN FUTURE MISCFLG
        AND #$95        ;  (AND TABBING, XOFF AND LF EAT BITS)
        PHA
        LDA #$09        ; CTL-I

INIT5: STA CMDBYTE,X   ; CMD ESC CHAR (IGNORED FOR SIC MODES)
        PLA
        STA MISCFLG,X   ; SET MISCFLG FLAGS
;
; NOW FOR THE ACIA INITIALIZATION ROUTINE
;
INITACIA: LDA ZPTMP2     ; DIPSW2
        PHA
        AND #$A0        ; DATA BIT OPTIONS FOR CIC MODE
        BVC INITACIA1   ; BRANCH FOR CIC MODE
        AND #$80        ; 8 DATA, 1 OR 2 STOP FOR SIC, PPC
INITACIA1: JSR DATACMD1  ; SET CONTROL REG
        JSR BAUDCMD1    ; SET DIPSWITCH BAUD RATE
        PLA
        AND #$0C        ; PARITY OPTIONS FOR CIC MODE
        BVC INITACIA2   ; BRANCH FOR CIC MODE
        LDA #$0         ; DISABLE PARITY FOR SIC, PPC MODES
INITACIA2: ASL A
        ASL A
        ASL A
        ORA #$0B
        STA CMDREG,Y
        LDA RDREG,Y     ; THROW OUT THE STRANGE STUFF
        RTS
;;;;;;;;;;;;;;;;;;;;;;;
; PASCAL READ ROUTINE ;
;;;;;;;;;;;;;;;;;;;;;;;
PASCALREAD: JSR PENTRY   ; SHARED BY BOTH PASCAL VERSIONS
PASCALREAD1: JSR GETCHAR ; GET ACIA/KBD DATA
        AND #$7F        ; CLEAR HIGH BIT FOR PASCAL
PASEXIT: LDY MSLOT
        LDX STSBYTE,Y   ; ERROR STATUS-> X-REG
        RTS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; GETCHAR ROUTINE WAITS FOR  ;
;  THE NEXT CHAR FROM EITHER ;
;  THE ACIA OR KEYBOARD (IF  ;
;  ENABLED).  USED BY PASCAL ;
;  READ ROUTINE, XON WAIT,   ;
;  AND ACK WAIT. DATA IS RE- ;
;  TURNED IN THE A=REGISTER  ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
GETCHAR: JSR INPUT       ; ACIA DATA?
        BCS GETCHAR1
        JSR CKKBD       ; KEYBOARD INPUT?
        BCC GETCHAR
GETCHAR1: RTS            ; EXIT WHEN WE HAVE SOMETHING

; HILEV.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; APPLE II SSC FIRMWARE         ;
;                               ;
;   BY LARRY KENYON             ;
;                               ;
;    -JANUARY 1981-             ;;;;;;;;;;;;;;
;                                            ;
; (C) COPYRIGHT 1981 BY APPLE COMPUTER, INC. ;
;                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; CIC, SIC, PPC MODE HIGH-LEVEL ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; CIC EXIT ROUTINE . . .        ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CICEXIT: JSR CHECKTERM   ; SEE IF WE'VE ENTERED TERMINAL MODE
;;;;;;;;;;;;;;;;;;;;;;
; BASIC EXIT ROUTINE ;
;;;;;;;;;;;;;;;;;;;;;;
BASICEXIT: PLA
        TAY
        PLA
        TAX
        JMP BEXIT
;;;;;;;;;;;;;;;;;;;;;;;
; BASIC INPUT ROUTINE ;
;;;;;;;;;;;;;;;;;;;;;;;
BINPUT: BEQ BINACIA     ; BRANCH IF NOT CIC MODE
        LDA BUFBYTE,X   ; INPUT BUFFER FULL?
        BPL BINKBD
        LSR BUFBYTE,X   ; RESET BUFFER FULL
        BNE BINACIA1    ; <ALWAYS>

BINKBD: JSR GETKBD      ; KEYBOARD DATA?
        BCC BINACIA

BINEND: LDA DELAYFLG,X
        AND #$C0        ; TRANSLATE LOWERCASE TO UPPERCASE?
        BEQ BINEND1     ; IF SO, LET THE MONITOR DO IT
        LDA CHARACTER   ; IF NOT, SET FLAG IF
        CMP #$E0        ;  THIS IS A LOWERCASE CHAR
        BCC BINEND1     ;  FOR INPUT BUFFER CORRECTION
        LDA STATEFLG,X  ;  (CIRCUMVENT APPLE MONITOR)
        ORA #$40
        STA STATEFLG,X

BINEND1: PLP
        BEQ BASICEXIT   ; BRANCH IF NOT CIC MODE
        BNE CICEXIT     ; <ALWAYS> CHECK TO SEE IF WE
                        ;  ENTERED TERM MODE (VIA KYBD ESCAPE)
BINACIA: JSR INPUT       ; ACIA DATA?
        BCC BINKBD
BINACIA1: JSR RESTORE    ; DO BASIC CURSED DUTY
        PLP
        PHP             ; GET CIC MODE INDICATOR
        BEQ BINEND      ; SKIP IF NOT CIC MODE
        JSR CKINPUT     ; LOOK FOR INPUT STREAM SPECIAL CHARS
        JMP BINEND
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; SIC, PPC BASIC OUTPUT ROUTINE ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SEROUT: JSR CMDSEQCK    ; CHECK FOR A COMMAND SEQUENCE
        BCS BASICEXIT   ; BRANCH IF WE WERE IN COMMAND MODE
        LDA CHARACTER   ; SAVE CHAR ON STACK
        PHA
        LDA MISCFLG,X   ; IF VIDEO OR TABBING ENABLED,
        AND #$C0        ;  DON'T MESS WITH THE CURSOR
        BNE TABCHECK

        LDA CH          ; CHECK FOR COMMA TABBING
        BEQ NOTAB       ; IF CH=0, THERE WAS NO TAB OR COMMA
        CMP #8          ; INTEGER BASIC COMMA?
        BEQ COMMA
        CMP #16         ; APPLESOFT COMMA?
        BNE TABCHECK
COMMA: ORA #$F0
        AND COLBYTE,X   ; SET COL TO PREVIOUS TAB
        CLC
        ADC CH          ; THEN INCREMENT TO NEXT TAB
        STA CH

TABCHECK: LDA COLBYTE,X
        CMP CH          ; IS TABBING NEEDED?
        BEQ NOTAB       ; IF EQUAL THEN NO TAB NEEDED
        LDA #$A0        ; SPACE FOR FORWARD TAB
        BCC TAB1
        LDA MISCFLG,X   ; DON'T BACKSPACE UNLESS TABBING
        ASL A           ;  OPTION IS ENABLED
        BPL NOTAB
        LDA #$88        ; BACKSPACE FOR BACKTAB
TAB1: STA CHARACTER
        BIT IORTS       ; SET V=1 TO INDICATE TABBING
        PHP             ; SAVE TABBING INDICATOR
        BVS TAB2        ; <ALWAYS> AROUND BATCH MOVE ENTRY
        NOP
;;;;;;;;;;;;;;;;;;;;;;;;
; SHORT BATCH MOVE:    ;
;  LOCATE AT $C93D FOR ;
;  COMPATIBILITY WITH  ;
;  SIC P8 BLOCK MOVE.  ;
;;;;;;;;;;;;;;;;;;;;;;;;
BATCHIN: BIT IORTS
        .byte $50         ; DUMMY BVC
BATCHOUT: CLV            ; V=0 FOR OUTPUT ENTRY
        LDX MSLOT
        JMP BATCHIO
;;;;;;;;;;;;;;
; BURP . . . ;
;;;;;;;;;;;;;;
TAB2: JSR ADJUST      ; ADJUST COLUMN COUNT
        JSR OUTPUT2     ; DON'T GO TO SCREEN WHEN TABBING
        JMP FORCECR     ; SHARE SOME CODE. . .

NOTAB: PLA
        CLV
        PHP             ; SAVE 'NO TAB' INDICATION
NOTAB1: STA CHARACTER   ; (FORCE CR REENTRY)
        PHA
        JSR OUTPUT1     ; ENTER AFTER CMD SEQ CHECK
        JSR ADJUST
        PLA
        EOR #$8D        ; WAS IT A CR?
        ASL A
        BNE FORCECR
        STA COLBYTE,X   ; IF SO, RESET COLUMN TO 0
        STA CH

FORCECR: LDA STATEFLG,X  ; FORCE CR DISABLED?
        BPL SEREND
        LDA PWDBYTE,X   ; FORCE CR IF LIMIT REACHED
        BEQ SEREND      ; (FOR P8 POKE COMPATIBILITY)
        CLC
        SBC COLBYTE,X
        LDA #$8D
        BCC NOTAB1      ; BRANCH TO FORCE CR

SEREND: PLP
        BVS TABCHECK    ; BRANCH IF TABBING

        LDA MISCFLG,X   ; DON'T MESS WITH CURSOR
        BMI SEREND2     ;  WHEN VIDEO IS ON
        LDY COLBYTE,X
        ASL A
        BMI SETCH       ; SET CH TO VALUE OF COL FOR TABBING
        TYA
        LDY #0
        SEC
        SBC PWDBYTE,X
        CMP #$F8        ; WITHIN 8 CHARS OF PWIDTH?
        BCC SETCH
        ADC #$27        ; IF SO, ADJUST TO WITHIN 8 OF 40
        TAY
SETCH: STY CH

SEREND2: JMP BASICEXIT   ; THAT'S ALL

;;;;;;;;;;;;;;;;;;;;;;;;
; PASCAL ENTRY ROUTINE ;
;;;;;;;;;;;;;;;;;;;;;;;;
PENTRY: STX MSLOT
        STY SLOT16
        LDA #0
        STA STSBYTE,X
        RTS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; SIC MODE PRINTER WIDTH TABLE ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
PWDTBL: .byte $29         ; 40 COLUMNS
        .byte $48         ; 72 COLUMNS
        .byte $50         ; 80 COLUMNS
        .byte $84         ; 132 COLUMNS
;;;;;;;;;;;;;;;;;;;;;;;;
; PASCAL WRITE ROUTINE ;
; (DOUBLES AS PASCAL   ;
;  1.0 ENTRY POINT)    ;
; -MUST BE AT SC9AA-   ;
;;;;;;;;;;;;;;;;;;;;;;;;
PASCALWRITE: STA CHARACTER
        JSR PENTRY
        JSR OUTPUT
        JMP PASEXIT     ; LOAD X-REG WITH ERROR BYTE & RTS

;;;;;;;;;;;;;;;;;;;;;;;;;
; COLUMN ADJUST ROUTINE ;
; (PPC, SIC MODES ONLY) ;
;;;;;;;;;;;;;;;;;;;;;;;;;
ADJUST: LDA CHARACTER
        EOR #$08        ; BACKSPACE?
        ASL A
        BEQ DECRCOL     ; IF SO, DECREMENT COLUMN
        EOR #$EE        ; DELETE? ($FF, RUB)
        BNE CTRLTST
DECRCOL: DEC COLBYTE,X   ; DECREMENT COLUMN COUNT
        BPL ADJRTS
        STA COLBYTE,X   ; DON'T ALLOW TO GO BELOW 0
ADJRTS: RTS
CTRLTST: CMP #$C0        ; DON'T INCREMENT COLUMN COUNT FOR
        BCS ADJRTS      ;  CONTROL CHARACTERS
        INC COLBYTE,X
        RTS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; ROUTINE TO PROCESS SPECIAL INPUT CHARS ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CKINPUT: LDA MISCFLG,X
        AND #$08        ; INPUT CTL CHARS ENABLED?
        BEQ CIEND

        LDA STATEFLG,X
        LDY CHARACTER
        CPY #$94        ; CTL-T?
        BNE CKINPUT1
        ORA #$80        ; SET TERMINAL MODE
        BNE CKINPUT2    ; <ALWAYS>

CKINPUT1: CPY #$92       ; CONTROL-R?
        BNE CIEND
        AND #$7F        ; RESET TERMINAL MODE
CKINPUT2: STA STATEFLG,X
CIEND: RTS

; TERM.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; APPLE II SSC FIRMWARE         ;
;                               ;
;   BY LARRY KENYON             ;
;                               ;
;    -JANUARY 1981-             ;;;;;;;;;;;;;;
;                                            ;
; (C) COPYRIGHT 1981 BY APPLE COMPUTER, INC. ;
;                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; SHORT BLOCK MOVE              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
BATCHIO: TXA
        ASL A
        ASL A
        ASL A
        ASL A
        STA SLOT16
        LDA #0
        STA STSBYTE,X   ; ZERO ERROR INDICATION
        BVS MOVIN

MOVOUT: LDY #0
        LDA (A1L),Y     ; GET BUFFER DATA
        STA CHARACTER
        JSR ACIAOUT     ; SEND IT OUT THE ACIA
        JSR NXTA1
        BCC MOVOUT
        RTS

MOVIN: JSR SRIN
        BCC MOVIN
        LDA RDREG,Y
        LDY #0
        STA (A1L),Y     ; PUT ACIA DATA INTO BUFFER
        JSR NXTA1
        BCC MOVIN
        RTS

;;;;;;;;;;;;;;;;;;;;;;;;;;
;                        ;
; TERMINAL MODE ROUTINES ;
;                        ;
;;;;;;;;;;;;;;;;;;;;;;;;;;
CHECKTERM: LDA STATEFLG,X ; HAVE WE ENTERED TERMINAL MODE?
        BPL TERMRTS     ; IF NOT, A SIMPLE RTS WILL DO. . .
;
; WE ENTER THE WORLD OF TERMINAL MODE
;
TERMMODE: LDA #$02       ; START IN SHIFT-LOCK STATE
        PHA             ; SHIFT STATE IS SAVED ON STACK
        LDA #$7F
        JSR KCMD1       ; RESET ECHO (DEFAULT TO FULL DUP)

TERMNEXT: LDY CH
        LDA (BASL),Y
        STA CHARACTER   ; SAVE SCREEN CHARACTER
TERMNEXT1: LDA #$07      ; IMPLEMENT A FLASHING UNDERLINE
        AND RNDH        ;  FOR A CURSOR
        BNE TERMNEXT3
        LDY CH
        LDA #$DF
        CMP (BASL),Y    ; IS UNDERLINE ON THE SCREEN?
        BNE TERMNEXT2   ; IF NOT, PUT IT THERE
        LDA CHARACTER   ; OTHERWISE USE TRUE SCREEN CHAR
TERMNEXT2: STA (BASL),Y
        INC RNDH        ; MAKE IT FLASH, BUT
        INC RNDH        ; NOT TOO SLOW AND NOT TOO FAST

TERMNEXT3: LDA STATEFLG,X ; ARE WE STILL IN TERM MODE?
        BMI TERMACIAIN  ; IF SO, GO CHECK ACIA

TERMEXIT: JSR RESTORE    ; ALWAYS REPLACE OUR CURSOR
        PLA             ; CLEAN UP THE STACK
        LDA #$8D        ; RETURN A <CR> TO COVER UP
        STA CHARACTER
TERMRTS: RTS

TERMACIAIN: JSR INPUT    ; ACIA INPUT?
        BCC TERMKBDIN   ; IF NOT, GO CHECK KEYBOARD
        JSR RESTORE     ; RESTORE CURSOR, INPUT->CHARACTER
        JSR CKINPUT     ; CHECK FOR CTL-T, CTL-R
        JSR SCREENOUT1  ; INPUT->SCREEN ALWAYS
        JMP TERMNEXT

TERMKBDIN: JSR GETKBD    ; KEYPRESS?
        BCC TERMNEXT1   ; SKIP IF NOT
        BVS TERMNEXT    ; BRANCH IF WE DID A KBD ESCAPE SEQ.
        LDA MISCFLG,X   ; SHIFTING ENABLED?
        ASL A
        BPL TERMSEND1
        PLA             ; RECOVER TERMSTATE
        TAY
        LDA CHARACTER
        CPY #1          ; 1 = SHIFT LETTERS, XLATE NUMBERS
        BEQ TERMCAP
        BCS TERMLOCK    ; 2 MEANS CAPS LOCK MODE

TERMNORM: CMP #$9B       ; ESC?
        BNE TERMLETTER

TERMINC: INY             ; INCREMENT STATE
TERMINC1: TYA
        PHA             ; PUT BACK ON STACK
        JMP TERMNEXT

TERMLETTER: CMP #$C1     ; <A?
        BCC TERMSEND
        CMP #$DB        ; >Z?
        BCS TERMSEND
        ORA #$20        ; IT'S A LETTER SO TRANSLATE TO LC
        STA CHARACTER

TERMSEND: TYA
        PHA             ; PUT STATE BACK ON STACK
TERMSEND1: JSR OUTPUT1   ; GO OUTPUT
        JMP TERMNEXT

TERMCAP: CMP #$9B        ; TWO ESCAPES?
        BEQ TERMINC
        CMP #$B0        ; <0?
        BCC TERMCAP1
        CMP #$BB        ; >COLON?
        BCS TERMCAP1
;
; ESC <NUMBER> SO TRANSLATE INTO MISSING ASCII CHAR
;
        TAY
        LDA TRANSLATE-$B0,Y
        STA CHARACTER
TERMCAP1: LDY #0         ; BACK TO STATE 0
        BEQ TERMSEND    ; <ALWAYS>

TERMLOCK: CMP #$9B       ; ESC?
        BNE TERMSEND
        LDY #0
        BEQ TERMINC1    ; <ALWAYS>

;;;;;;;;;;;;;;;;;;;
; TRANSLATE TABLE ;
;;;;;;;;;;;;;;;;;;;
TRANSLATE: .byte $9B       ; ESC
        .byte $9C         ; FS
        .byte $9F         ; US
        .byte $DB         ; LEFT BRACKET
        .byte $DC         ; LEFT SLASH
        .byte $DF         ; UNDERSCORE
        .byte $FB         ; LEFT ENCLOSE
        .byte $FC         ; VERTICAL BAR
        .byte $FD         ; RIGHT ENCLOSE
        .byte $FE         ; TILDE
        .byte $FF         ; RUB

; CORE.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; APPLE II SSC FIRMWARE         ;
;                               ;
;   BY LARRY KENYON             ;
;                               ;
;    -JANUARY 1981-             ;;;;;;;;;;;;;;
;                                            ;
; (C) COPYRIGHT 1981 BY APPLE COMPUTER, INC. ;
;                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; CORE SUBROUTINES              ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; GENERAL PURPOSE WAIT ROUTINE ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; WAITMS WAITS FOR [A-REG] MILLISECONDS (256 IF A-REG=0)
;
WAITMS: LDX #202
WAITMS1: DEX             ; <DON'T LET THIS LOOP CROSS A PAGE>
        BNE WAITMS1     ; 5 MICROSECOND LOOP
        SEC
        SBC #01
        BNE WAITMS
        LDX MSLOT
        RTS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; ACIA STATUS REGISTER READ ROUTINES ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; SRIN USED TO CHECK ACIA INPUT STATUS
;
SRIN: LDY SLOT16      ; SLOT16=$N0
        LDA STREG,Y
        PHA
        AND #$20        ; DCD?
        LSR A           ; AN ERROR IF NOT
        LSR A
        STA ZPTEMP
        PLA
        AND #$0F
        CMP #$08        ; SET CARRY IF RDR FULL, ELSE CLEAR
        BCC SRIN1
        AND #$07        ; PE, FE, OVR VALID ONLY WHEN RDR=1
        BCS SRIN2       ; <ALWAYS>
SRIN1: LDA ZPTEMP
SRIN2: ORA ZPTEMP      ; GET DCD ERROR BIT
        BEQ SRIN3       ; BRANCH IF NO ERRORS FOUND
        ORA #$20        ; ELSE SET BIT 5 TO OFFSET FOR PASCAL
        STA STSBYTE,X   ; AND SAVE IN STATUS TEMP
SRIN3: RTS             ; CY=1 MEANS DATA IS AVAILABLE
;
; SROUT CHECKS IF TDR IS EMPTY + HARDWARE HANDSHAKE IS OK
;
SROUT: LDY SLOT16
        LDA STREG,Y
        AND #$70
        CMP #$10        ; EQU IF TDR EMPTY, DCD, DSR, & CTS
        RTS

;;;;;;;;;;;;;;;;;;;;;;;;;
; GENERAL INPUT ROUTINE ;
;;;;;;;;;;;;;;;;;;;;;;;;;
INPUT: JSR SRIN
        BCC NOINPUT1

        LDA RDREG,Y     ; GET THE ACIA INPUT
        ORA #$80        ; SET HI BIT FOR BASIC
        CMP #$8A        ; LINEFEED?
        BNE INPUT2

        TAY
        LDA MISCFLG,X   ; SEE IF WE SHOULD EAT IT
        AND #$20
        BNE NOINPUT     ; IF SO, JUST KEEP IT A SECRET
        TYA

INPUT2: SEC             ; INDICATE DATA
        RTS

NOINPUT: CLC             ; CARRY CLEAR FOR NO INPUT
NOINPUT1: RTS

;;;;;;;;;;;;;;;;;;;;;;;;;;
; GENERAL OUTPUT ROUTINE ;
;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; START OF COMMAND CHECK ROUTINE
;
CMDSEQCK: LDY SLOT16
        LDA DIPSW1,Y
        LSR A
        BCS NOCMD       ; DON'T WORRY ABOUT CMD SEQ FOR SIC
        LDA STATEFLG,X
        AND #$07        ; ARE WE IN A COMMAND SEQUENCE?
        BEQ ESCCHECK
        JSR CMDPROC     ; IF SO, GOTO COMMAND CENTRAL
        SEC             ; INDICATE COMMAND
        RTS

ESCCHECK: LDA CHARACTER
        AND #$7F        ; IGNORE HIGH BIT
        CMP CMDBYTE,X   ; IS THIS BEGINNING OF A CMD SEQ?
        BNE XOFFCK
        INC STATEFLG,X  ; START UP COMMAND MODES
        SEC             ; INDICATE COMMAND
        RTS

XOFFCK: LDA MISCFLG,X   ; IS XON ENABLED?
        AND #$08
        BEQ NOCMD       ; SKIP THIS IF NOT

        JSR INPUT       ; ANY INPUT?
        BCC NOCMD       ; IF NOT, GO OUTPUT
        CMP #$93        ; IS IT AN XOFF?
        BEQ XONWAIT     ; IF SO, GO WAIT FOR ANOTHER INPUT
        PHA
        LDA MISCFLG,X   ; CIC MODE?
        LSR A
        LSR A
        PLA
        BCC ANRTS
        STA BUFBYTE,X   ; IF SO, WE HAVE A BUFFER
NOCMD: CLC             ; INDICATE NOT A CMD SEQ
ANRTS: RTS

XONWAIT: JSR GETCHAR     ; GET ACIA/KBD DATA
        CMP #$91        ; IS IT AN XON?
        BNE XONWAIT     ; IF NOT, WAIT
        CLC             ; OTHERWISE, INDICATE NOT A CMD SEQ
        RTS             ;  AND RETURN
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; NOW THE OUTPUT ROUTINE YOU'VE BEEN WAITING FOR ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
OUTPUT: JSR CMDSEQCK
        BCS ANRTS       ; DON'T OUTPUT COMMAND SEQUENCES

OUTPUT1: JSR SCREENOUT

OUTPUT2: LDY SLOT16
        LDA DIPSW1,Y
        LSR A
        BCC OUTPUT3     ; SKIP ETX/ACK FOR NATIVE MODES
        LSR A
        BCC OUTPUT3     ; BRANCH IF NOT P8A EMULATION

;;;;;;;;;;;;;;;;;;;;;
; P8A ETX/ACK STUFF ;
;;;;;;;;;;;;;;;;;;;;;
; AFTER 148 CHARACTERS BUT NOT WITHIN AN ESCAPE SEQUENCE
; OF UP TO 5 CHARACTERS, THE HANDSHAKE IS PERFORMED
; (WILL DELAY UNTIL 'NOT ESC' AND THEN 4 MORE CHARS
;  OR UNTIL AN 'ESC')

P8AOUT1: LDA CHARACTER   ; SAVE CHAR ON STACK
        PHA
        LDA HANDSHKE,X  ; CHAR COUNT FOR BUFFER FULL
        CMP #103        ; IF <103 THEN 153 CHARS IN BUFFER
        BCC ETX
        CMP #108        ; IF >=108 THEN LESS THAN 149 CHARS
        BCS P8AOUT2     ;  SO NO HANDSHAKE IS NEEDED YET
        CMP #107        ; SETS CARRY IF 107 (149 SENT)
        PLA
        PHA
        EOR #$9B        ; ESC?
        AND #$7F        ; IGNORE HI-BIT
        BNE P8AOUT2     ; COUNT AS 1 OF 5 IF NOT 'ESC'
        BCS P8AOUT3     ; DON'T COUNT IF 149TH CHAR IS 'ESC'

ETX: LDA STATEFLG,X  ; SEND QUERY CHAR TO PRINTER
        AND #$1F        ; (DEFAULT IS ETX)
        ORA #$80
        STA CHARACTER
        JSR ACIAOUT
ACK: JSR GETCHAR     ; GET ACIA/KBD DATA
        EOR #$86        ; ACK?
        BNE ETX         ; IF NOT ACK, REPEAT HANDSHAKE
        STA HANDSHKE,X  ; INIT CHAR COUNT TO 255

P8AOUT2: DEC HANDSHKE,X
P8AOUT3: PLA             ; GET REAL CHAR TO OUTPUT
        STA CHARACTER
        EOR #$8D        ; IF CR AND CR DELAY MODE
        ASL A
        BNE P8AOUT4     ;  THEN FAKE CHAR COUNT TO LESS THAN
        LDA DELAYFLG,X  ;  48 TO FORCE HANDSHAKE ON NEXT
        AND #$30        ;  CHARACTER OUT
        BEQ P8AOUT4
        STA HANDSHKE,X

P8AOUT4: JSR ACIAOUT
        JMP LFGEN       ; (SKIP DELAYS)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; AND BACK TO NORMAL OUTPUT ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
OUTPUT3: JSR ACIAOUT     ; OUTPUT THE CHARACTER
;
; NOW CHECK FOR CR, LF, AND FF DELAYS
;
        ASL A
        TAY
        LDA DELAYFLG,X  ; GET DELAY FLAGS
        CPY #$18        ; FORM FEED?
        BEQ OUTDLY1
        LSR A
        LSR A           ; RIGHT JUSTIFY LF DELAY
        CPY #$14        ; LINE FEED?
        BEQ OUTDLY1
        LSR A
        LSR A           ; RIGHT JUSTIFY CR DELAY
        CPY #$1A        ; CARRIAGE RETURN?
        BNE OUTPUTEND
OUTDLY1: AND #$03        ; JUST WANT LOWEST 2 BITS
        BEQ LFGEN       ; NO DELAY INDICATED
        TAY
        LDA DLYTBL-1,Y
        TAY             ; DELAY IN 32 MSEC INCREMENTS
OUTDLYLP: LDA #32
        JSR WAITMS
        DEY
        BNE OUTDLYLP
;
; CHECK ON LF GENERATION OPTION
;
LFGEN: LDA CHARACTER
        ASL A
        CMP #$1A        ; CARRIAGE RETURN?
        BNE OUTPUTEND
        LDA MISCFLG,X   ; IS LF GENERATE ENABLED?
        ROR A
        BCC OUTPUTEND
        LDA #$8A
        STA CHARACTER   ; LINE FEED
        JMP OUTPUT2     ; (DON'T ECHO IT)
OUTPUTEND: RTS

DLYTBL: .byte $01         ; 32 MSEC
        .byte $08         ; 1/4 SEC
        .byte $40         ;  2  SEC
;;;;;;;;;;;;;;;;;;;;;;;
; ACIA OUTPUT ROUTINE ;
;;;;;;;;;;;;;;;;;;;;;;;
ACIAOUT: JSR SROUT       ; READY FOR OUTPUT?
        BNE ACIAOUT
        TYA
        ORA #<TDREG+1   ; PREPARE TO ADDRESS ACIA,
        TAY             ;  CAUSING 6502 FALSE READ TO OCCUR
        LDA CHARACTER   ;  ON PAGE $BF (AVOIDING RDR READ)
        STA $BFFF,Y     ; HERE YOU ARE ACIA
        RTS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; RESTORE CURSOR (NOT FOR PASCAL) ;
; (A-REG SHOULD CONTAIN NEW CHAR) ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
RESTORE: PHA             ; SAVE NEW CHARACTER
        LDY CH
        LDA CHARACTER   ; OLD CHARACTER
        STA (BASL),Y
        PLA

        CMP #$95        ; SCREEN PICK?
        BNE RESTOREND
        LDA CHARACTER   ; IF SO, USE SCREEN CHAR
        CMP #$20        ; INVERSE?
        BCS RESTOREND
        JSR GETXLATE    ; REVERSE THE TRANSLATION
        EOR REVMASK,Y
RESTOREND: STA CHARACTER
        RTS

; UTIL.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; APPLE II SSC FIRMWARE         ;
;                               ;
;   BY LARRY KENYON             ;
;                               ;
;    -JANUARY 1981-             ;;;;;;;;;;;;;;
;                                            ;
; (C) COPYRIGHT 1981 BY APPLE COMPUTER, INC. ;
;                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; UTILITY ROUTINES              ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; PASCAL-BASIC KEYBOARD FETCH ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CKKBD: CLC             ; RETURN CARRY CLEAR FOR NO DATA
        LDA MISCFLG,X
        AND #$04        ; ANSWER NO IF KEYBOARD IS DISABLED
        BEQ CKKBDXIT

CKKBD1: LDA KBD
        BPL CKKBDXIT
        STA KBDSTRB
        SEC             ; INDICATE DATA
CKKBDXIT: RTS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; GET A CHAR FROM KEYBOARD FOR BASIC ONLY ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
GETKBD: INC RNDL        ; MIX UP RANDOM # SEED
        BNE GETKBD1     ;  FOR BASIC
        INC RNDH
GETKBD1: JSR CKKBD       ; KEYBOARD FETCH ROUTINE
        CLV             ; INDICATE NO ESCAPE SEQUENCE
        BCC CKKBDXIT    ; EXIT IF NO KEY PRESS
        JSR RESTORE     ; DO BASIC CURSED DUTY
        AND #$7F
        CMP CMDBYTE,X   ; IS IT THE START OF A COMMAND?
        BNE GETKBDONE   ; IF NOT, EXIT INDICATING DATA
        LDY SLOT16
        LDA DIPSW1,Y    ; ONLY DO CMD ESC FOR PPC, SIC MODES
        LSR A
        BCS GETKBDONE
;;;;;;;;;;;;;;;;;;;;;;;;;;;
; KEYBOARD ESCAPE HANDLER ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;
KBDESC: LDY #$A         ; FIRST PRINT A PROMPT
PROMPTLOOP: LDA PROMPTBL,Y
        STA CHARACTER
        TYA
        PHA
        JSR SCREENOUT1  ; ALWAYS SEND TO SCREEN
        PLA
        TAY
        DEY
        BPL PROMPTLOOP

        LDA #1          ; START OUT IN COMMAND STATE 1
        JSR SETOSTATE

GETCMD: JSR CKKBD1      ; WAIT FOR KEYBOARD CHARACTER
        BPL GETCMD
        CMP #$88        ; BACKSPACE?
        BEQ KBDESC      ; IF SO, THEN START OVER
        STA CHARACTER

        JSR SCREENOUT1
        JSR CMDSEQCK    ; PUMP THRU CMD INTERPRETER

        LDA STATEFLG,X  ; ARE WE DONE?
        AND #$07
        BNE GETCMD      ; IF NOT, GO AGAIN

        LDA #$8D        ; FORCE BACK A CARRIAGE RETURN
        STA CHARACTER
        BIT IORTS       ; INDICATE THAT A CMD SEQ HAS OCCURRED
GETKBDONE: SEC           ; INDICATE SUCCESS
        RTS

PROMPTBL: .byte $3A, $43, $53, $53, $20, $45, $4C, $50, $50, $41
        .byte $8D

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; ROUTINE TO PRINT A CHARACTER ON THE CURRENT DISPLAY ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SCREENOUT: LDA MISCFLG,X
        BPL NOOUT       ; IF SCREEN DISABLED

SCREENOUT1: LDA MISCFLG,X ; ENTRY AFTER ECHO CHECK
        AND #$02        ; IF IT ISN'T CIC MODE,
        BEQ ASCREEN     ; ALWAYS USE THE APPLE SCREEN
        LDA STATEFLG,X  ; CURRENT SCREEN = APPLE SCREEN?
        AND #$38
        BEQ ASCREEN     ; SLOT O= APPLE SCREEN

        TXA             ; JUMP TO CN00 SPACE
        PHA
        LDA #<SENDCD-1  ;  TO VECTOR TO THE PERIPHERAL
        PHA             ;  IN THE CHAIN SLOT
NOOUT: RTS
;
; APPLE 40-COL SCREEN DRIVER
;
ASCREEN: JSR GETXLATE    ; GET THE TRANSLATE OPTIONS
        ORA #$80        ; SET HIGH BIT OF CHAR
        CMP #$E0        ; LOWERCASE?
        BCC TESTLETTER
        EOR LCMASK,Y    ; DO LOWERCASE TRIP
TOSCREEN: JMP VIDOUT     ; ALL REGS ARE PRESERVED
;
; IF UPPERCASE, WE ONLY MAP LETTERS
;
TESTLETTER: CMP #$C1     ; <A?
        BCC TOSCREEN
        CMP #$DB        ; >Z?
        BCS TOSCREEN
        EOR UCMASK,Y
        BCC TOSCREEN    ; <ALWAYS>

; MASKS FOR CASE TRANSLATION
LCMASK: .byte $20,$00,$E0,$20
UCMASK: .byte $00,$00,$00,$C0
REVMASK: .byte $00,$00,$E0,$C0

GETXLATE: LDA DELAYFLG,X ; TRANSLATE OPTIONS IN B6-B7
        ROL A
        ROL A
        ROL A
        AND #$03
        TAY
        LDA CHARACTER
        RTS

; CMD.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; APPLE II SSC FIRMWARE         ;
;                               ;
;   BY LARRY KENYON             ;
;                               ;
;    -JANUARY 1981-             ;;;;;;;;;;;;;;
;                                            ;
; (C) COPYRIGHT 1981 BY APPLE COMPUTER, INC. ;
;                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; SSC COMMAND PROCESSOR         ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; COMMAND TABLE (USED BY COMMAND PROCESSER ROUTINE ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CMDTBL: .byte $42         ; B(REAK)
        .byte $67         ; CIC     PAS  NS=7
        .byte <BREAKCMD-1
        .byte $54         ; T(ERMINAL)
        .byte $47         ; CIC          NS=7
        .byte <TERMCMD-1
        .byte $43         ; C(R GENERATE)
        .byte $87         ;     PPC      NS=7
        .byte <TERMCMD-1
        .byte $51         ; Q( UIT)
        .byte $47         ; CIC          NS=7
        .byte <QUITCMD-1
        .byte $52         ; R ESET)
        .byte $C7         ; CIC PPC      NS=7
        .byte <RESETCMD-1
        .byte $5A         ; Z COMMAND
        .byte $E7         ; CIC PPC PAS  NS=7
        .byte <ZCMD-1
        .byte $49         ; I COMMAND
        .byte $90         ;     PPC      NS=0
        .byte <ICMD-1
        .byte $4B         ; K COMMAND
        .byte $90         ;     PPC      NS=0
        .byte <KCMD-1

        .byte $45         ; E(CHO)
        .byte $43         ; CIC          NS=3
        .byte $80
        .byte $46         ; F(ROMKYBD)
        .byte $E3         ; CIC PPC PAS  NS=3
        .byte $04
        .byte $4C         ; L(F GENERATE)
        .byte $E3         ; CIC PPC PAS  NS=3
        .byte $01
        .byte $58         ; X(OFF)
        .byte $E3         ; CIC PPC PAS  NS=3
        .byte $08
        .byte $54         ; T(ABBING)
        .byte $83         ;     PPC      NS=3
        .byte $40
        .byte $53         ; S(HIFTING)
        .byte $43         ; CIC          NS=3
        .byte $40
        .byte $4D         ; M(UNCH LF)
        .byte $E3         ; CIC PPC PAS  NS=3
        .byte $20

        .byte $00         ; END OF FIRST PART MARKER

CMDTBL1: .byte $42         ; B(AUD)
        .byte $F6         ; CIC PPC PAS  NS=6
        .byte <BAUDCMD-1
        .byte $50         ; P(ARITY)
        .byte $F6         ; CIC PPC PAS  NS=6
        .byte <PARITYCMD-1
        .byte $44         ; D(ATA)
        .byte $F6         ; CIC PPC PAS  NS=6
        .byte <DATACMD-1
        .byte $46         ; F(F DELAY)
        .byte $F6         ; CIC PPC PAS  NS=6
        .byte <FFCMD-1
        .byte $4C         ; L(F DELAY)
        .byte $F6         ; CIC PPC PAS  NS=6
        .byte <LFCMD-1
        .byte $43         ; C(R DELAY)
        .byte $F6         ; CIC PPC PAS  NS=6
        .byte <CRCMD-1
        .byte $54         ; T(RANSLATE)
        .byte $D6         ; CIC PPC      NS=6
        .byte <TRANCMD-1
        .byte $4E         ; N COMMAND
        .byte $90         ;     PPC      NS=0
        .byte <NCMD-1
        .byte $53         ; S(CREENSLOT)
        .byte $56         ; CIC          NS=6
        .byte <SSLOTCMD-1

        .byte $00         ; END OF TABLE MARKER

;;;;;;;;;;;;;;;;;;;;;;
; COMMAND ROUTINES   ;
; (CALLED BY PARSER) ;
; (MUST START IN     ;
;  PAGE $CD . . . )  ;
;;;;;;;;;;;;;;;;;;;;;;
TRANCMD: LDA #$3F        ; SET SCREEN TRANSLATE OPTIONS
        LDY #$7
        BNE DELAYSET    ; <ALWAYS>
CRCMD: LDA #$CF        ; SET CR DELAY
        LDY #$5
        BNE DELAYSET    ; <ALWAYS>

LFCMD: LDA #$F3        ; SET LF DELAY
        LDY #$3
        BNE DELAYSET    ; <ALWAYS>

FFCMD: LDA #$FC        ; SET FF DELAY
        LDY #$1
DELAYSET: AND DELAYFLG,X ; DON'T DISTURB THE OTHER FLAGS
        STA ZPTMP1
        LDA PARAMETER,X
        AND #$03        ; JUST USE TWO BITS
        CLC
        ROR A           ; ONCE FOR FUN
ROTATE: ROL A           ; CHANGE DIRECTIONS
        DEY
        BNE ROTATE      ; PREPARE IT TO OR INTO THE FLAGS

        ORA ZPTMP1
        STA DELAYFLG,X
        RTS

SSLOTCMD: AND #$7        ; SET SLOT COMMAND
        ASL A
        ASL A
        ASL A
        STA ZPTMP1
        ASL A
        CMP SLOT16      ; MAKE SURE WE DON'T SET IT
        BEQ SSLOTCMD1   ;  TO OUR OWN SLOT
        LDA STATEFLG,X
        AND #$C7        ; PUT NEW SLOT NUMBER IN BITS 3-5
        ORA ZPTMP1      ;  OF CMDBYTE,X
        STA STATEFLG,X
        LDA #0          ; STORE ZERO INTO
        STA CHNBYTE,X   ; SLOT OFFSET (SET TO CN00 ENTRY)
SSLOTCMD1: RTS

BAUDCMD: AND #$0F        ; SET NEW BAUD RATE
        BNE BAUDCMD2
BAUDCMD1: LDA DIPSW1,Y   ; ZERO PARM = RELOAD FROM SWITCHES
        LSR A
        LSR A
        LSR A
        LSR A
BAUDCMD2: ORA #$10       ; SET INT. BAUD RATE GENERATOR
        STA ZPTMP1
        LDA #$E0
CTLREGSET: STA ZPTMP2
        LDA CTLREG,Y
        AND ZPTMP2
        ORA ZPTMP1
        STA CTLREG,Y
        RTS

PARITYCMD: DEY           ; TRICK: SO CTLREG,Y ACTUALLY
                        ;  ADDRESSES THE COMMAND REG

DATACMD: ASL A           ; SET NEW # OF DATA BITS
        ASL A
        ASL A
        ASL A
        ASL A
DATACMD1: STA ZPTMP1
        LDA #$1F
        BNE CTLREGSET   ; <ALWAYS>

TERMCMD: ASL STATEFLG,X  ; SET TERMINAL MODE
        SEC
        BCS QCMD1       ; <ALWAYS>

RESETCMD: STA RESET,Y    ; DROP RTS, DTR
        JSR SETSCR      ; PR#0
        JSR SETKBD      ; IN#O
        LDX MSLOT
QUITCMD: ASL STATEFLG,X  ; CLEAR TERMINAL MODE
        CLC
QCMD1: ROR STATEFLG,X
        RTS

BREAKCMD: LDA CMDREG,Y   ; SEND BREAK SIGNAL
        PHA             ;  FOR 233 MILLISECONDS
        ORA #$0C
        STA CMDREG,Y
        LDA #233        ; DELAY FOR 233 MICROSEC.
        JSR WAITMS
        PLA             ; RESTORE OLD COMMAND REG CONTENTS
        STA CMDREG,Y
        RTS

ICMD: LDA #$28
        STA PWDBYTE,X   ; SET PRINTER WIDTH TO 40
        LDA #$80
        ORA MISCFLG,X   ; SET SCREEN ECHO
        BNE KCMD2       ; <ALWAYS>

KCMD: LDA #$FE        ; RESET THE LF GENERATE FLAG
KCMD1: AND MISCFLG,X
KCMD2: STA MISCFLG,X
        RTS

NCMD: CMP #40         ; >=40?
        BCC ZCMDRTS     ; IF NOT, JUST EXIT
        STA PWDBYTE,X   ; SET NEW PRINTER WIDTH
        LDA #$3F        ; DISABLE SCREEN, SET LISTING MODE
        BNE KCMD1       ; <ALWAYS>

ZCMD: ASL CMDBYTE,X   ; DISABLE COMMAND RECOGNITION
        SEC
        ROR CMDBYTE, X
ZCMDRTS: RTS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; VECTOR ACCORDING TO COMMAND STATE ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CMDPROC: TAY             ; A-REG=COMMAND STATE
        LDA CHARACTER
        AND #$7F

        CMP #$20        ; SKIP SPACES FOR ALL MODES
        BNE CMDPROC2
        CPY #$3         ; EXCEPT MODE 3
        BEQ CMDPROC1
        RTS
CMDPROC1: LDA #$4
        BNE SETOSTATE   ; <ALWAYS>

CMDPROC2: CMP #$0D       ; CARRIAGE RETURN?
        BNE CMDPROC4
        JSR ZEROSTATE   ; ABORT FOR STATES 0-5, EXIT FOR 6,7
        CPY #$07        ; IN STATE 7 WE VECTOR TO THE PROC
        BEQ CMDPROC3
        RTS             ; OTHERWISE, JUST EXIT

CMDPROC3: LDA #$CD       ; ALL PROCS MUST START IN PAGE $CD
        PHA
        LDA PARAMETER,X
        PHA
        LDY SLOT16      ; NEEDED BY BREAK CMD
        RTS

CMDPROC4: STA ZPTEMP
        LDA #$CE        ; ALL ROUTINES MUST START
        PHA             ;  IN PAGE SCE
        LDA STATETBL,Y
        PHA
        LDA ZPTEMP
        RTS             ; RTS TO COMMAND PROCEDURE
;
; NOW THE STATE ROUTINES
;
;;;;;;;;;;;;;;;;;;;;;;
; STATE BRANCH TABLE ;
;;;;;;;;;;;;;;;;;;;;;;
STATETBL: .byte <STATERR-1 ; BAD STATE
        .byte <CSTATE1-1  ; <CMD> SEEN
        .byte <CSTATE2-1  ; ACCUMULATE PARAMETER
        .byte <CDONE-1    ; SKIP UNTIL SPACE
        .byte <CSTATE4-1  ; E/D SOMETHING
        .byte <STATERR-1  ; ILLEGAL STATE
        .byte <CDONE-1    ; SKIP UNTIL CR
        .byte <CDONE-1    ; SKIP UNTIL CR THEN DO CMD
;;;;;;;;;;;;;;;;;;;
; COMMAND STATE 1 ;
;;;;;;;;;;;;;;;;;;;
CSTATE1: CMP CMDBYTE,X   ; IS IT <CMD>?
        BNE CSTATE1A
        DEC STATEFLG,X  ; SET STATE BACK TO ZERO
        JMP ACIAOUT     ; OUTPUT <CMD> IF SO

CSTATE1A: CMP #$30       ; >=0?
        BCC CSTATE1B
        CMP #$3A        ; <=9?
        BCS CSTATE1B
        AND #$0F        ; IT'S A NUMBER
        STA PARAMETER,X
        LDA #2
        BNE SETOSTATE   ; <ALWAYS> SET MODE 2 AND RETURN

CSTATE1B: CMP #$20       ; IS IT A CONTROL CHAR?
        BCS CSTATE1C
        STA CMDBYTE,X   ; SET NEW COMMAND CHARACTER
        JMP ZEROSTATE   ; RESET STATE TO ZERO

CSTATE1C: LDY #0         ; USE COMMAND TABLE
        BEQ CMDSEARCH   ; <ALWAYS>
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; COMMAND STATE 2: ACCUMULATE PARAMETER ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CSTATE2: EOR #$30        ; CONVERT $30-$39 TO 0-9
        CMP #$A         ; 0-9?
        BCS CSTATE2A
        LDY #$A         ; IT'S A NUMBER, SO ADD
ACCLOOP: ADC PARAMETER,X ;  IT TO 10*PARAMETER
        DEY
        BNE ACCLOOP
        STA PARAMETER, X
        BEQ CDONE       ; <ALWAYS>

CSTATE2A: LDY #CMDTBL1-CMDTBL ; USE COMMAND TABLE
        BNE CMDSEARCH   ; <ALWAYS>
;;;;;;;;;;;;;;;;;;;;;
; SET COMMAND STATE ;
;;;;;;;;;;;;;;;;;;;;;
ZEROSTATE: LDA #0
SETOSTATE: STA ZPTMP1
        LDX MSLOT
        LDA STATEFLG,X
        AND #$F8
        ORA ZPTMP1
        STA STATEFLG,X
CDONE: RTS
;;;;;;;;;;;;;;;;;;;;;;;;;
; COMMAND STATE 4 (E/D) ;
;;;;;;;;;;;;;;;;;;;;;;;;;
CSTATE4: TAY             ; E/D -> Y-REG
        LDA PARAMETER,X
        CPY #$44        ; D(ISABLE)?
        BEQ CSTATE4A
        CPY #$45        ; E(NABLE)?
        BNE STATERR     ; IF NOT, IGNORE THIS COMMAND
        ORA MISCFLG,X   ; SET FLAG
        BNE CSTATE4B    ; <ALWAYS>
CSTATE4A: EOR #$FF       ; INVERT FOR DISABLE
        AND MISCFLG,X   ; RESET FLAG
CSTATE4B: STA MISCFLG,X
;;;;;;;;;;;;;;;;;;;;;
; ESCAPE TO STATE 6 ;
;;;;;;;;;;;;;;;;;;;;;
SETSTATE6: LDA #6
        BNE SETOSTATE   ; <ALWAYS>
STATERR: LDA #32         ; CODE FOR BAD COMMAND
        STA STSBYTE,X
        BNE SETSTATE6   ; <ALWAYS>
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; TABLE DRIVEN COMMAND PROCESSOR ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CMDSEARCH: LDA CMDTBL,Y  ; GET CANDIDATE CHARACTER
        BEQ STATERR     ; A ZERO MARKS THE END OF A SUBTABLE
        CMP ZPTEMP      ; MATCH?
        BEQ CMDMATCH
        INY
CMDSEARCH1: INY          ; REENTRY FOR WRONG MODES
        INY             ; ENTRY LENGTH = 3
        BNE CMDSEARCH   ; <ALWAYS>

CMDMATCH: INY
        LDA CMDTBL,Y
        STA ZPTMP1
        AND #$20        ; CHECK PASCAL ENABLE
        BNE CMDMATCH1   ; IT'S ON SO DONT CHECK P-BIT
        LDA MISCFLG,X   ; OFF SO MAKE SURE
        AND #$10        ;  THAT WE AREN'T IN PASCAL
        BNE CMDSEARCH1  ; BRANCH IF WE ARE

CMDMATCH1: LDA MISCFLG,X ; GET CIC/PPC BIT
        LSR A           ; SHIFT CIC/PPC MODE BIT TO CARRY
        LSR A
        BIT ZPTMP1      ; PPC=>N CIC=>V
        BCS CMDMATCH2   ; BRANCH IF CIC MODE
        BPL CMDSEARCH1  ; NOT OK FOR PPC
        BMI CMDEXEC     ; AND OK
CMDMATCH2: BVC CMDSEARCH1 ; NOT OK FOR CIC

CMDEXEC: LDA ZPTMP1      ; RETRIEVE TABLE MODE BYTE
        PHA
        AND #$07
        JSR SETOSTATE   ; SET NEXT STATE
        INY
        PLA
        AND #$10
        BNE CMDEXEC1    ; IF BIT 4 IS SET, VECTOR TO ROUTINE
        LDA CMDTBL,Y
        STA PARAMETER,X
        RTS

CMDEXEC1: LDA #$CD       ; ROUTINES MUST BE IN PAGE $CD
        PHA
        LDA CMDTBL,Y
        PHA
        LDY SLOT16
        LDA PARAMETER,X ; LOT OF ROUTINES NEED THIS
        RTS

        .byte $C2

; CF00 common page (banked entries stubbed).

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; APPLE II SSC FIRMWARE         ;
;                               ;
;   BY LARRY KENYON             ;
;                               ;
;    -JANUARY 1981-             ;;;;;;;;;;;;;;
;                                            ;
; (C) COPYRIGHT 1981 BY APPLE COMPUTER, INC. ;
;                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                               ;
; CF00 SPACE                    ;
;                               ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        .org $CF00

;;;;;;;;
; BOOT ;
;;;;;;;;
BOOT: RTS             ; no disk boot on the SSC card

PDBOOT: RTS

;;;;;;;;;;;;;;;;;;
; COMMON HANDLER ;
;;;;;;;;;;;;;;;;;;
COMMON: RTS             ; no ProDOS/SmartPort driver on the SSC card

;;;;;;;;;;;;;;;
; COMMON QUIT ;
;;;;;;;;;;;;;;;
QUIT: RTS

;;;;;;;;;;;;;;;;;;;;;;;
; READ 512-BYTE BLOCK ;
;;;;;;;;;;;;;;;;;;;;;;;

RDBLOCK: RTS             ; no block driver on the SSC card
                        ; (the a2retronet bank-2/3 page stubs do not
                        ; exist here; BANKSET writes are ignored ROM
                        ; space on this card)

;;;;;;;;;;
; CONFIG ;
;;;;;;;;;;
CFG: RTS             ; a2retronet config tool is not supported

;;;;;;;;;;;;;;;;;;;;;;;;
; BASIC INITIALIZATION ;
;;;;;;;;;;;;;;;;;;;;;;;;
BINIT: STA BENTER      ; ENTER A2RETRONET BASIC MODE
        BVC NORMIO
        ASL CMDBYTE,X   ; ALWAYS ENABLE COMMANDS
        LSR CMDBYTE,X
        LDA CMDREG,Y    ; JUST HAD A POWER-ON OR PROGRAM RESET?
        AND #$1F
        BNE BINIT1
        LDA #$EF        ; IF SO, GO JOIN INIT IN PROGRESS
        JSR INIT1

BINIT1: CPX CSWH
        BNE FROMIN
        LDA #<OENTRY
        CMP CSWL        ; IF CSW IS ALREADY POINTING TO OENTRY,
        BEQ FROMIN      ;  THEN WE MUST HAVE COME FROM KSW
        STA CSWL        ; OTHERWISE, SET CSW TO OENTRY
FROMOUT: CLC             ; INDICATE WE ARE CALLED FOR OUTPUT
        BCC NORMIO      ; <ALWAYS>
FROMIN: CPX KSWH        ; MAKE SURE KSW POINTS HERE
        BNE FROMOUT     ;
        LDA #<IENTRY
        STA KSWL        ; SET UP KSW (NOTE CARRY SET FROM CPX)
;
; BRANCH TO APPROPRIATE BASIC I/O ROUTINE
;
NORMIO: LDA MISCFLG,X   ; SEPARATE CIC MODE FROM OTHERS
        AND #$02        ; NOT ZERO FOR CIC MODE
        PHP             ; SAVE CIC MODE INDICATION
        BCC BOUTPUT
        JMP BINPUT

BOUTPUT: LDA STATEFLG,X  ; CHECK FOR AFTER LOWERCASE INPUT
        PHA
        ASL A
        BPL BOUTPUT1    ; SKIP IF NOT
        LDX ZPTEMP
        LDA CHARACTER
        ORA #$20
        STA INBUFF,X    ; RESTORE LOWERCASE IN BUFFER
        STA CHARACTER   ; AND FOR OUTPUT ECHO
        LDX MSLOT
BOUTPUT1: PLA
        AND #$BF        ; ZERO THE FLAG
        STA STATEFLG,X
        PLP             ; RETRIEVE CIC MODE INDICATION
        BEQ BOUTPUT2    ; BRANCH FOR PPC, SIC MODES
        JSR OUTPUT      ; CIC MODE OUTPUT
        JMP CICEXIT     ; FINISH BY CHECKING FOR TERM MODE

BOUTPUT2: JMP SEROUT

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; RETURN FROM BASIC ENTRIES ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
BEXIT: LDA CHARACTER
        STA BLEAVE      ; LEAVE A2RETRONET BASIC MODE
        RTS

        .res $D000-*
