"""Build the virtual Super Serial Card firmware ROM for slot 1.

Assembles the real Apple SSC firmware (Larry Kenyon, 1981; a2retronet source
split) with SLOT=1 and SSC=1 into two .mem images for hdl/apple/ssc_card.sv:

  - ssc_slot1_c100.mem : the $C100-$C1FF slot page
  - ssc_c800.mem       : the $C800-$CFFF expansion ROM (2 KB)

The a2retronet CF00 tail banks between SSC and SmartPort firmware. The
Appletini SSC card serves one unbanked image with no disk function, so the
banked entries (BOOT/PDBOOT/COMMON/QUIT/RDBLOCK/CFG) are stubbed to RTS.
Everything else, including the whole serial core and command processor, is
the reference source untouched.

The page-placement asserts below are load-bearing: the command processor
dispatches by pushing a hard-coded $CD/$CE page byte, and Pascal 1.0 jumps
to fixed entry addresses, so any drift in encoding must fail the build.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from build_smartport_rom import (  # noqa: E402
    REPO_ROOT,
    SSC_PATH,
    CN00_PATH,
    CF00_PATH,
    assemble_source,
    convert_line_syntax,
    preprocess_conditional_source,
    replace_exact_block,
    write_mem,
)

C800_PATH = REPO_ROOT / "6502_SSC.C800.S"
HILEV_PATH = REPO_ROOT / "6502_SSC.HILEV.S"
TERM_PATH = REPO_ROOT / "6502_SSC.TERM.S"
CORE_PATH = REPO_ROOT / "6502_SSC.CORE.S"
UTIL_PATH = REPO_ROOT / "6502_SSC.UTIL.S"
CMD_PATH = REPO_ROOT / "6502_SSC.CMD.S"

ASM_OUTPUT_PATH = REPO_ROOT / "hdl" / "apple" / "ssc_slot1.asm"
SLOT_MEM_PATH = REPO_ROOT / "hdl" / "apple" / "ssc_slot1_c100.mem"
CONT_MEM_PATH = REPO_ROOT / "hdl" / "apple" / "ssc_c800.mem"

SLOT = 1
SSC = 1

# Pascal 1.0 fixed entry points, documented in the reference source.
PASCAL10_READ_ADDR = 0xC84D
PASCAL10_BATCH_ADDR = 0xC93D
PASCAL10_WRITE_ADDR = 0xC9AA

# CMDPROC pushes these page bytes before an RTS dispatch, so every command
# routine must live in $CD00-$CDFF and every state routine in $CE00-$CEFF.
CMD_PAGE = 0xCD
STATE_PAGE = 0xCE
CMD_ROUTINES = [
    "TRANCMD", "CRCMD", "LFCMD", "FFCMD", "SSLOTCMD", "BAUDCMD",
    "PARITYCMD", "DATACMD", "TERMCMD", "RESETCMD", "QUITCMD",
    "BREAKCMD", "ICMD", "KCMD", "NCMD", "ZCMD",
]
STATE_ROUTINES = ["STATERR", "CSTATE1", "CSTATE2", "CSTATE4", "CDONE"]


def stub_a2retronet_banked_entries(cf00_lines: list[str]) -> list[str]:
    """Replace the banked SmartPort hand-offs with RTS stubs.

    The SSC image has no bank 1, so the BOOT1/SWITCH/CFGHDLR targets do not
    exist. The exact-match blocks keep this loud if the reference moves.
    """
    lines = cf00_lines
    lines = replace_exact_block(
        lines,
        [
            "BOOT    LDA #$01        ; SMARTPORT FIRMWARE",
            "        STA BANKSET",
            "        JMP BOOT1",
        ],
        ["BOOT    RTS             ; no disk boot on the SSC card"],
        "BOOT bank hand-off",
    )
    lines = replace_exact_block(
        lines,
        [
            "PDBOOT  JSR PRODOS",
            "        LDA #$01        ; SMARTPORT FIRMWARE",
            "        STA BANKSET",
            "        JMP BOOT2",
        ],
        ["PDBOOT  RTS"],
        "PDBOOT bank hand-off",
    )
    lines = replace_exact_block(
        lines,
        [
            "COMMON  LDA #$01        ; SMARTPORT FIRMWARE",
            "        STA BANKSET",
            "        JMP SWITCH",
        ],
        ["COMMON  RTS             ; no ProDOS/SmartPort driver on the SSC card"],
        "COMMON bank hand-off",
    )
    lines = replace_exact_block(
        lines,
        [
            "QUIT    STA BANKCLR",
            "        RTS",
        ],
        ["QUIT    RTS"],
        "QUIT bank clear",
    )
    lines = replace_exact_block(
        lines,
        [
            "RDBLOCK JMP RDBLK1      ; Appletini has an unbanked C8 image so the",
        ],
        ["RDBLOCK RTS             ; no block driver on the SSC card"],
        "RDBLOCK dispatch",
    )
    lines = replace_exact_block(
        lines,
        [
            "CFG     LDA #$01        ; SMARTPORT FIRMWARE",
            "        STA BANKSET",
            "        JSR CFGHDLR",
            "        STA BANKCLR",
            "        RTS",
        ],
        ["CFG     RTS             ; a2retronet config tool is not supported"],
        "CFG bank hand-off",
    )
    return lines


def preprocess_ssc_source() -> str:
    cond_symbols = {"SLOT": SLOT, "SSC": SSC}

    merged: list[str] = [
        "; This file is generated by scripts/build_ssc_rom.py",
        "; Source of truth:",
        ";   - 6502_SSC.CN00.S",
        ";   - 6502_SSC.C800.S / .HILEV.S / .TERM.S / .CORE.S / .UTIL.S / .CMD.S",
        ";   - 6502_SSC.CF00.S (a2retronet banked entries stubbed to RTS)",
        ";",
        "; Slot-1 SSC build: the full Apple serial firmware, one unbanked image.",
        "",
        f"SLOT = {SLOT}",
        f"SSC = {SSC}",
        "",
    ]

    for line in SSC_PATH.read_text().splitlines():
        if line.strip().startswith(".REPEAT"):
            break
        stripped = line.strip()
        if not stripped:
            merged.append("")
            continue
        if (stripped.startswith(".FEATURE") or stripped.startswith(".MACPACK")
                or stripped.startswith(".DEFINE")):
            continue
        merged.append(convert_line_syntax(line))

    merged.extend(["", "; Slot page ($C100).", ""])
    merged.extend(preprocess_conditional_source(
        CN00_PATH.read_text().splitlines(), cond_symbols))

    for title, path in [
        ("C800 high level", C800_PATH),
        ("HILEV", HILEV_PATH),
        ("TERM", TERM_PATH),
        ("CORE", CORE_PATH),
        ("UTIL", UTIL_PATH),
        ("CMD", CMD_PATH),
    ]:
        merged.extend(["", f"; {title}.", ""])
        merged.extend(preprocess_conditional_source(
            path.read_text().splitlines(), cond_symbols))

    merged.extend(["", "; CF00 common page (banked entries stubbed).", ""])
    cf00_raw = stub_a2retronet_banked_entries(
        CF00_PATH.read_text().splitlines())
    merged.extend(preprocess_conditional_source(cf00_raw, cond_symbols))

    return "\n".join(merged) + "\n"


def check_layout(slot_data: bytearray,
                 cont_data: bytearray,
                 symbols: dict[str, int]) -> None:
    # Pascal 1.1 serial-card signature bytes on the slot page.
    if slot_data[0x05] != 0x38 or slot_data[0x07] != 0x18:
        raise ValueError(
            f"slot page lost the Pascal serial signature: "
            f"C105=${slot_data[0x05]:02X} C107=${slot_data[0x07]:02X}")
    if slot_data[0x0B] != 0x01 or slot_data[0x0C] != 0x31:
        raise ValueError(
            f"slot page lost the generic/device signature: "
            f"C10B=${slot_data[0x0B]:02X} C10C=${slot_data[0x0C]:02X}")
    if slot_data[0xF0] != 0x20:
        raise ValueError("CONFIG entry did not land at $C1F0")
    if slot_data[0xFF] != (symbols["DISK"] & 0xFF):
        raise ValueError("$C1FF must hold the low byte of DISK")

    fixed = {
        "PREAD0": PASCAL10_READ_ADDR,
        "BATCHIN": PASCAL10_BATCH_ADDR,
        "PASCALWRITE": PASCAL10_WRITE_ADDR,
    }
    for name, addr in fixed.items():
        if symbols[name] != addr:
            raise ValueError(
                f"{name} landed at ${symbols[name]:04X}, "
                f"reference requires ${addr:04X}")

    for name in CMD_ROUTINES:
        if (symbols[name] >> 8) != CMD_PAGE:
            raise ValueError(
                f"command routine {name} landed at ${symbols[name]:04X}; "
                f"CMDPROC dispatch requires page ${CMD_PAGE:02X}")
    for name in STATE_ROUTINES:
        if (symbols[name] >> 8) != STATE_PAGE:
            raise ValueError(
                f"state routine {name} landed at ${symbols[name]:04X}; "
                f"CMDPROC dispatch requires page ${STATE_PAGE:02X}")

    for name in ("BINIT", "BEXIT", "BOOT", "COMMON", "CFG"):
        if not (0xCF00 <= symbols[name] <= 0xCFFF):
            raise ValueError(
                f"{name} landed at ${symbols[name]:04X}, outside $CFxx")

    if len(slot_data) != 0x100 or len(cont_data) != 0x800:
        raise ValueError("unexpected image sizes")


def build() -> tuple[bytearray, bytearray, dict[str, int], str]:
    source_text = preprocess_ssc_source()
    slot_data, cont_data, symbols = assemble_source(
        source_text, include_symbols=True, slot_base=0xC100)
    check_layout(slot_data, cont_data, symbols)
    return slot_data, cont_data, symbols, source_text


def main() -> None:
    slot_data, cont_data, symbols, source_text = build()
    ASM_OUTPUT_PATH.write_text(source_text)
    write_mem(SLOT_MEM_PATH, slot_data)
    write_mem(CONT_MEM_PATH, cont_data)
    used = max(symbols[name] for name in symbols
               if 0xC800 <= symbols[name] < 0xD000)
    print(f"SSC ROM: slot page + C8 image built, "
          f"highest CF symbol ${used:04X}")
    print(f"Wrote {ASM_OUTPUT_PATH}")
    print(f"Wrote {SLOT_MEM_PATH}")
    print(f"Wrote {CONT_MEM_PATH}")


if __name__ == "__main__":
    main()
