#!/usr/bin/env python3
"""Generate Disk II mechanical sound sample assets from Assets/Sounds WAVs."""

from __future__ import annotations

import wave
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SOUND_DIR = REPO_ROOT / "Assets" / "Sounds"
SAMPLES_C = REPO_ROOT / "ps_sources" / "frontend" / "disk2_sound_samples.c"
SAMPLES_H = REPO_ROOT / "ps_sources" / "frontend" / "disk2_sound_samples.h"
PKG_SV = REPO_ROOT / "hdl" / "apple" / "disk2_sound_pkg.sv"

SOUNDS = [
    ("DOOR_OPEN", "01_door_open.wav"),
    ("DOOR_CLOSE", "02_door_close.wav"),
    ("TRACK0_RECAL", "03_track0_recal.wav"),
    ("IDLE_SPIN", "04_idle_spin.wav"),
    ("SEEK_34_0", "05_seek_34_0.wav"),
    ("SEEK_0_34", "06_seek_0_34.wav"),
]

SAMPLE_RATE_HZ = 48000
SEEK_FULL_QTRACK_DISTANCE = 35 * 4
SEEK_SOUND_NAMES = {
    "SEEK_34_0",
    "SEEK_0_34",
}


def read_wav_samples(path: Path) -> list[int]:
    with wave.open(str(path), "rb") as wav:
        if wav.getnchannels() != 1:
            raise ValueError(f"{path.name}: expected mono WAV")
        if wav.getframerate() != SAMPLE_RATE_HZ:
            raise ValueError(f"{path.name}: expected {SAMPLE_RATE_HZ} Hz WAV")
        if wav.getsampwidth() != 2:
            raise ValueError(f"{path.name}: expected 16-bit PCM WAV")
        frames = wav.readframes(wav.getnframes())

    samples = []
    for offset in range(0, len(frames), 2):
        value = int.from_bytes(frames[offset : offset + 2], "little", signed=True)
        samples.append(value & 0xFFFF)
    return samples


def write_header(total_samples: int) -> None:
    lines = [
        "#ifndef DISK2_SOUND_SAMPLES_H",
        "#define DISK2_SOUND_SAMPLES_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define DISK2_SOUND_SAMPLE_RATE_HZ {SAMPLE_RATE_HZ}U",
        f"#define DISK2_SOUND_SAMPLE_COUNT {total_samples}U",
        "#define DISK2_SOUND_SAMPLE_BYTES "
        "(DISK2_SOUND_SAMPLE_COUNT * (uint32_t)sizeof(uint16_t))",
        "",
    ]
    for index, (name, _filename) in enumerate(SOUNDS):
        lines.append(f"#define DISK2_SOUND_ID_{name} {index}U")
    lines.extend(
        [
            "",
            "extern const uint16_t disk2_sound_samples[DISK2_SOUND_SAMPLE_COUNT];",
            "",
            "#endif",
            "",
        ]
    )
    SAMPLES_H.write_text("\n".join(lines), encoding="ascii", newline="\n")


def write_samples(samples: list[int]) -> None:
    lines = [
        "/* Generated by scripts/build_disk2_sound_assets.py from Disk II WAV assets. */",
        '#include "disk2_sound_samples.h"',
        "",
        "const uint16_t disk2_sound_samples[DISK2_SOUND_SAMPLE_COUNT]",
        "    __attribute__((aligned(64))) = {",
    ]
    for offset in range(0, len(samples), 8):
        chunk = samples[offset : offset + 8]
        lines.append("    " + ", ".join(f"0x{sample:04X}U" for sample in chunk) + ",")
    lines.extend(["};", ""])
    SAMPLES_C.write_text("\n".join(lines), encoding="ascii", newline="\n")


def write_package(descriptors: list[tuple[str, int, int]], total_samples: int) -> None:
    lines = [
        "`timescale 1ns / 1ps",
        "",
        "// Generated by scripts/build_disk2_sound_assets.py from Assets/Sounds/*.wav.",
        "package disk2_sound_pkg;",
        "",
        f"    localparam int unsigned DISK2_SOUND_COUNT = {len(descriptors)};",
        f"    localparam int unsigned DISK2_SOUND_SAMPLE_COUNT = {total_samples};",
        f"    localparam int unsigned DISK2_SOUND_SAMPLE_RATE_HZ = {SAMPLE_RATE_HZ};",
        "",
    ]
    for index, (name, _offset, _length) in enumerate(descriptors):
        lines.append(f"    localparam logic [2:0] DISK2_SOUND_{name} = 3'd{index};")
    lines.extend(
        [
            "",
            "    function automatic logic [17:0] disk2_sound_offset(input logic [2:0] index);",
            "        case (index)",
        ]
    )
    for index, (name, offset, _length) in enumerate(descriptors):
        lines.append(f"            DISK2_SOUND_{name}: disk2_sound_offset = 18'd{offset};")
    lines.extend(
        [
            "            default: disk2_sound_offset = 18'd0;",
            "        endcase",
            "    endfunction",
            "",
            "    function automatic logic [17:0] disk2_sound_length(input logic [2:0] index);",
            "        case (index)",
        ]
    )
    for index, (name, _offset, length) in enumerate(descriptors):
        lines.append(f"            DISK2_SOUND_{name}: disk2_sound_length = 18'd{length};")
    lines.extend(
        [
            "            default: disk2_sound_length = 18'd0;",
            "        endcase",
            "    endfunction",
            "",
            f"    localparam logic [7:0] DISK2_SOUND_SEEK_FULL_QTRACK_DISTANCE = 8'd{SEEK_FULL_QTRACK_DISTANCE};",
            "",
            "    function automatic logic [17:0] disk2_sound_seek_position_offset(",
            "        input logic [2:0] index,",
            "        input logic [7:0] position",
            "    );",
            "        logic [7:0] capped_position;",
            "        begin",
            "            if (position > DISK2_SOUND_SEEK_FULL_QTRACK_DISTANCE)",
            "                capped_position = DISK2_SOUND_SEEK_FULL_QTRACK_DISTANCE;",
            "            else",
            "                capped_position = position;",
            "",
            "            unique case (index)",
        ]
    )
    for _index, (name, _offset, length) in enumerate(descriptors):
        if name not in SEEK_SOUND_NAMES:
            continue
        lines.append(f"                DISK2_SOUND_{name}: begin")
        lines.append("                    unique case (capped_position)")
        for position in range(0, SEEK_FULL_QTRACK_DISTANCE + 1):
            seek_offset = (
                length * position + (SEEK_FULL_QTRACK_DISTANCE // 2)
            ) // SEEK_FULL_QTRACK_DISTANCE
            lines.append(
                "                        "
                f"8'd{position}: disk2_sound_seek_position_offset = "
                f"18'd{seek_offset};"
            )
        lines.append(
            "                        "
            f"default: disk2_sound_seek_position_offset = 18'd{length};"
        )
        lines.append("                    endcase")
        lines.append("                end")
    lines.extend(
        [
            "                default: disk2_sound_seek_position_offset = 18'd0;",
            "            endcase",
            "        end",
            "    endfunction",
            "",
            "endpackage",
            "",
        ]
    )
    PKG_SV.write_text("\n".join(lines), encoding="ascii", newline="\n")


def main() -> int:
    all_samples: list[int] = []
    descriptors: list[tuple[str, int, int]] = []

    for name, filename in SOUNDS:
        path = SOUND_DIR / filename
        if not path.exists():
            raise FileNotFoundError(path)
        offset = len(all_samples)
        samples = read_wav_samples(path)
        if len(samples) > 0x3FFFF:
            raise ValueError(f"{filename}: too many samples for 18-bit sample address")
        descriptors.append((name, offset, len(samples)))
        all_samples.extend(samples)

    if len(all_samples) > 0x3FFFF:
        raise ValueError(f"total Disk II sample set is too large: {len(all_samples)} samples")

    write_header(len(all_samples))
    write_samples(all_samples)
    write_package(descriptors, len(all_samples))

    print(f"wrote {SAMPLES_C.relative_to(REPO_ROOT)} ({len(all_samples)} samples)")
    print(f"wrote {SAMPLES_H.relative_to(REPO_ROOT)}")
    print(f"wrote {PKG_SV.relative_to(REPO_ROOT)} ({len(descriptors)} descriptors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
