#!/usr/bin/env python3
"""Generate fixed CP437 and DEC-special tables from Terminus BDF files."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "ps_sources" / "frontend" / "linear_text_overlay_font.c"
FONT_ROOT = ROOT / "third_party" / "terminus-font-4.49.1"
FONT_8X14 = FONT_ROOT / "ter-u14n.bdf"
FONT_8X16 = FONT_ROOT / "ter-u16n.bdf"

CP437_CONTROL = (
    " \u263a\u263b\u2665\u2666\u2663\u2660\u2022\u25d8\u25cb\u25d9\u2642\u2640\u266a\u266b\u263c"
    "\u25ba\u25c4\u2195\u203c\u00b6\u00a7\u25ac\u21a8\u2191\u2193\u2192\u2190\u221f\u2194\u25b2\u25bc"
)
DEC_SPECIAL = (
    " \u25c6\u2592\u2409\u240c\u240d\u240a\u00b0\u00b1\u2424\u240b\u2518\u2510\u250c\u2514\u253c"
    "\u23ba\u23bb\u2500\u23bc\u23bd\u251c\u2524\u2534\u252c\u2502\u2264\u2265\u03c0\u2260\u00a3\u00b7"
)


def cp437_char(value: int) -> str:
    if value < 32:
        return CP437_CONTROL[value]
    if value == 127:
        return "\u2302"
    return bytes((value,)).decode("cp437")


def load_bdf(path: Path, expected_height: int) -> dict[int, tuple[int, ...]]:
    """Read all 8-pixel-wide Unicode glyphs from one Terminus BDF file."""
    glyphs: dict[int, tuple[int, ...]] = {}
    encoding: int | None = None
    width = 0
    height = 0
    bitmap: list[int] | None = None

    for raw_line in path.read_text(encoding="ascii").splitlines():
        line = raw_line.strip()
        if line.startswith("ENCODING "):
            encoding = int(line.split()[1])
        elif line.startswith("BBX "):
            fields = line.split()
            width = int(fields[1])
            height = int(fields[2])
        elif line == "BITMAP":
            bitmap = []
        elif line == "ENDCHAR":
            if (encoding is not None and encoding >= 0 and width == 8 and
                    height == expected_height and bitmap is not None and
                    len(bitmap) == expected_height):
                glyphs[encoding] = tuple(bitmap)
            encoding = None
            width = 0
            height = 0
            bitmap = None
        elif bitmap is not None:
            bitmap.append(int(line, 16))

    return glyphs


def map_chars(glyphs: dict[int, tuple[int, ...]],
              chars: list[str],
              label: str) -> list[tuple[int, ...]]:
    rows: list[tuple[int, ...]] = []
    for index, ch in enumerate(chars):
        codepoint = ord(ch)
        if codepoint not in glyphs:
            raise SystemExit(
                f"{label} entry {index} needs missing U+{codepoint:04X}")
        rows.append(glyphs[codepoint])
    return rows


def emit_table(name: str, glyphs: list[tuple[int, ...]], height: int) -> str:
    lines = [f"const uint8_t {name}[{len(glyphs)}][{height}] = {{"]
    for index, rows in enumerate(glyphs):
        values = ", ".join(f"0x{value:02X}" for value in rows)
        lines.append(f"    {{ {values} }}, /* {index:3d} */")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    for path in (FONT_8X14, FONT_8X16):
        if not path.is_file():
            raise SystemExit(f"missing source font: {path}")

    tables: list[tuple[str, list[tuple[int, ...]], int]] = []
    for height, path in ((14, FONT_8X14), (16, FONT_8X16)):
        source = load_bdf(path, height)
        cp437 = map_chars(source,
                          [cp437_char(value) for value in range(256)],
                          f"CP437 8x{height}")
        dec = map_chars(source, list(DEC_SPECIAL), f"DEC 8x{height}")
        tables.extend((
            (f"linear_text_overlay_cp437_font_8x{height}", cp437, height),
            (f"linear_text_overlay_dec_font_8x{height}", dec, height),
        ))

    text = """/* Generated by scripts/gen_linear_text_overlay_font.py.
 *
 * These fixed bitmaps derive from Terminus Font 4.49.1 by Dimitar
 * Toshkov Zhekov. Terminus Font uses the SIL Open Font License 1.1.
 * See third_party/terminus-font-4.49.1/OFL.TXT.
 */

#include <stdint.h>

"""
    text += "\n\n".join(emit_table(name, glyphs, height)
                          for name, glyphs, height in tables)
    text += "\n"
    OUTPUT.write_text(text, encoding="ascii")
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
