"""Generate ps_sources/frontend/applicard_rom.c/.h from an Applicard Z80
boot ROM dump (2 KB). The embedded array is the default ROM; the service
still honors an SD override at 0:/APPLICARD.ROM.

Usage: python scripts/gen_applicard_rom_c.py [path-to-rom]
Default input: software/applicard/APPLICARD.ROM
"""

import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROM_SIZE = 2048


def main():
    rom_path = Path(sys.argv[1]) if len(sys.argv) > 1 else (
        ROOT / "software" / "applicard" / "APPLICARD.ROM")
    data = rom_path.read_bytes()
    if len(data) != ROM_SIZE:
        raise SystemExit(f"{rom_path}: expected {ROM_SIZE} bytes, "
                         f"got {len(data)}")
    crc = zlib.crc32(data) & 0xFFFFFFFF

    lines = []
    for off in range(0, ROM_SIZE, 12):
        chunk = data[off:off + 12]
        lines.append("    " + " ".join(f"0x{b:02X}," for b in chunk))
    body = "\n".join(lines)

    header = f"""/* Generated by scripts/gen_applicard_rom_c.py -- do not edit.
 *
 * PCPI Appli-Card Z80 boot ROM (applicard-v9.bin), 2 KB,
 * CRC32 {crc:08x}. Source dump: Apple II Documentation Project /
 * MAME romset a2applicard.
 */

#ifndef APPLICARD_ROM_H
#define APPLICARD_ROM_H

#include <stdint.h>

#define APPLICARD_ROM_BYTES 2048U

extern const uint8_t applicard_rom[APPLICARD_ROM_BYTES];

#endif /* APPLICARD_ROM_H */
"""

    source = f"""/* Generated by scripts/gen_applicard_rom_c.py -- do not edit.
 *
 * PCPI Appli-Card Z80 boot ROM (applicard-v9.bin), 2 KB,
 * CRC32 {crc:08x}.
 */

#include "applicard_rom.h"

const uint8_t applicard_rom[APPLICARD_ROM_BYTES] = {{
{body}
}};
"""

    out_dir = ROOT / "ps_sources" / "frontend"
    (out_dir / "applicard_rom.h").write_text(header, encoding="ascii")
    (out_dir / "applicard_rom.c").write_text(source, encoding="ascii")
    print(f"wrote applicard_rom.c/.h (CRC32 {crc:08x})")


if __name__ == "__main__":
    main()
