# launch_amp.tcl -- AMP-aware JTAG launch for the Appletini One frontend.
#
# Vitis's GUI/launch.json flow does not properly handle our AMP flow. This
# script launches CPU0 only; CPU0 copies the embedded CPU1 image and wakes CPU1.
#
#   1. Connect to JTAG, reset system, program bitstream.
#   2. Run ps7_init / ps7_post_config and verify DDR is writable.
#   3. Download frontend.elf to CPU0 and start CPU0.
#   4. CPU0 copies the embedded frontend_core1 blob to 0x20000000 and wakes CPU1.
#
# Usage from the repo root:
#
#   xsdb scripts/launch_amp.tcl
#
# Override paths via env vars if your tree layout differs:
#   BIT_FILE, FRONTEND_ELF
#
# Reference: XAPP1079 "Simple AMP: Bare-Metal on Both Cortex-A9".

# ---------- Path resolution ----------

set repo_root [pwd]

proc envOrDefault {name default} {
    global env
    if {[info exists env($name)]} {
        return $env($name)
    }
    return $default
}

set BIT_FILE  [envOrDefault BIT_FILE \
    "$repo_root/project/appletini_yarz.runs/impl_1/appletini_yarz_top.bit"]
set FRONTEND_ELF [envOrDefault FRONTEND_ELF \
    "$repo_root/vitis_workspace/frontend/build/frontend.elf"]
set PS7_INIT_TCL [envOrDefault PS7_INIT_TCL \
    "$repo_root/vitis_workspace/frontend/_ide/psinit/ps7_init.tcl"]

foreach {var path} [list \
        BIT_FILE             $BIT_FILE \
        FRONTEND_ELF         $FRONTEND_ELF \
        PS7_INIT_TCL         $PS7_INIT_TCL] {
    if {![file exists $path]} {
        puts "ERROR: $var not found at $path"
        exit 1
    }
}

proc probeDdr {phase} {
    puts "==> Probing DDR ($phase)"
    if {[catch {mwr 0x00100000 0xA5A55A5A} err]} {
        puts "ERROR: DDR write failed during $phase"
        puts "       $err"
        exit 1
    }
    if {[catch {mrd 0x00100000 1} err]} {
        puts "ERROR: DDR read failed during $phase"
        puts "       $err"
        exit 1
    }
}

# ---------- Connect ----------

puts "==> Connecting to JTAG"
connect

# ---------- System reset ----------

puts "==> Resetting system via APU target"
# Different xsdb releases accept different reset scopes. -ps (works
# in some), -system (older), or just `rst` against the APU target
# (current default). Pick the APU first since rst works there.
targets -set -nocase -filter {name =~ "APU"}
rst

# ---------- ps7_init + bitstream ----------

# ps7_init.tcl is generated by Vitis platform build; sourcing it
# defines the ps7_init/ps7_post_config procs used below.
source $PS7_INIT_TCL

puts "==> Selecting CPU0"
targets -set -nocase -filter {name =~ "ARM*Cortex-A9 MPCore #0"}

puts "==> Programming bitstream"
fpga -file $BIT_FILE

# After fpga -file, the PS may deassert reset and CPU0 starts executing
# whatever it finds (BootROM -> flash firmware, if QSPI is programmed).
# ps7_init's mask_write operations need debug access to the PLL/CRF/CRL
# registers, which the DAP cannot serve while CPU0 is running -- it
# reports "APB AP transaction error" and bails. Explicitly halt CPU0
# before ps7_init so the debug transport is usable.
puts "==> Halting CPU0"
if {[catch {stop} err]} {
    # `stop` errors if CPU is already halted; that's fine, ignore.
    puts "    (already halted: $err)"
}

puts "==> Running ps7_init"
ps7_init
ps7_post_config
probeDdr "after ps7_init"

# ---------- CPU0 = frontend.elf ----------

puts "==> Loading frontend.elf on CPU0"
dow $FRONTEND_ELF
con
after 1000

puts "==> AMP launch complete. Both cores running."
puts "    CPU0 should print boot banner on UART0."
puts "    CPU0 starts CPU1 from the embedded frontend_core1 image."
